//! Reading code for the known-hash sync artifacts.
//!
//! These functions generate, on demand and from the finalized state, the
//! deterministic byte artifacts that known-hash-syncing nodes download and
//! verify against the SHA-256 constants pinned in `zebra-chain`:
//!
//! - **known-hash chunks** ([`known_hash_chunk_bytes`]): a `chunk_v2` encoding
//!   of a 150,000-block span (block hashes, size hints, and the sapling/orchard
//!   tree roots that update within the span).
//!
//! Every artifact is a deterministic function of the chain, so every honest
//! node produces byte-identical output that hashes to the pinned SHA-256
//! constants in `zebra-chain`.

use zebra_chain::{
    block::Height,
    parameters::{
        known_hashes::{
            chunk_v2::{self, TreeRoot},
            KnownHashListSpec, HASHES_PER_CHUNK, SIZE_HINT_UNIT, TREE_FRONTIER_MIN_NOTES,
        },
        spentness_hints::{self, MaxCheckpoint, SpentnessHints},
        Network,
    },
};

use tracing::warn;

use crate::{constants::MAX_BLOCK_REORG_HEIGHT, service::finalized_state::ZebraDb};

/// Returns the `chunk_v2` bytes for known-hash chunk `index`, or `None` if the
/// span has no finalized blocks.
///
/// If the chunk has already been downloaded-and-verified into the
/// `known_hash_chunk` column family, its stored bytes are returned directly.
/// Otherwise the bytes are generated on demand from the finalized state, and
/// a complete chunk's bytes are cached in the column family, so the expensive
/// generation runs at most once per chunk.
///
/// A chunk covers the `HASHES_PER_CHUNK`-block span starting at
/// `index * HASHES_PER_CHUNK`. The span is truncated at the reorg safety
/// margin below the finalized tip — served heights stop at
/// `tip - MAX_BLOCK_REORG_HEIGHT`, mirroring [`super::block::sync_hashes`], so
/// the generated bytes cannot be invalidated by an ordinary reorg. A chunk in
/// the pinned list is also truncated at the list's max height, so the final
/// partial chunk regenerates at exactly its pinned length; only a complete
/// chunk can hash to a pinned constant, and only complete chunks are cached.
///
/// Returns `None` when the span base is above the last finalized height (the
/// chunk is entirely in the future), so the caller reports the chunk as
/// unavailable instead of producing an empty chunk that could never match a
/// pinned hash.
pub fn known_hash_chunk_bytes(db: &ZebraDb, index: u32) -> Option<Vec<u8>> {
    // Prefer the stored, already-verified chunk if it is resident in the CF.
    if let Some(stored) = db.known_hash_chunk(index) {
        return Some(stored);
    }

    let tip_height = db.finalized_tip_height()?;

    // The span base is `index * HASHES_PER_CHUNK`. Use a checked multiply on the
    // untrusted `index` so a huge index can't overflow into a valid-looking
    // height; an overflow means the span is far in the future, so `None`.
    let span_base = index.checked_mul(HASHES_PER_CHUNK)?;

    // Serve only finalized heights: the span ends at the reorg safety margin
    // below the tip. Nothing in this span is final yet when the base is above
    // the margin.
    let max_served_height = tip_height.0.saturating_sub(MAX_BLOCK_REORG_HEIGHT);
    if span_base > max_served_height {
        return None;
    }

    // The span covers `[span_base, span_end]`, truncated at the last finalized
    // height. `span_base + HASHES_PER_CHUNK - 1` cannot overflow because
    // `span_base` is a multiple of `HASHES_PER_CHUNK` no greater than
    // `tip_height.0` (a u32 block height), so it is well within `u32::MAX`.
    let span_full_last = span_base + HASHES_PER_CHUNK - 1;
    let mut span_last = span_full_last.min(max_served_height);

    // The pinned lists end in a partial chunk: clamp the span end at the
    // pinned list's max height, so the final chunk regenerates at exactly its
    // pinned length and hashes to its pinned content address. Indices past
    // the pinned list are not clamped.
    let pinned_last = KnownHashListSpec::for_network(&db.network())
        // The cast is lossless: chunk indices are u32, far below usize.
        .filter(|spec| (index as usize) < spec.chunk_count())
        .map(|spec| spec.max_height.0);
    if let Some(pinned_last) = pinned_last {
        span_last = span_last.min(pinned_last);
    }

    // The cast is lossless: span lengths are at most `HASHES_PER_CHUNK`.
    let mut blocks: Vec<([u8; 32], u8)> = Vec::with_capacity((span_last - span_base + 1) as usize);
    for height in span_base..=span_last {
        let block_hash = db.hash(Height(height))?;

        // The size hint quantizes the serialized block size into
        // `size.div_ceil(SIZE_HINT_UNIT)`, capped at the `DEFAULT_SIZE_HINT`
        // loosest bound; it is always an upper bound on the block's size.
        // The sync metadata's fixed-size record carries the same serialized
        // size, so generation does not deserialize blocks. Missing metadata
        // (an incomplete backfill) makes the chunk unavailable.
        let metadata = db.sync_metadata(Height(height))?;
        // The cast is lossless: block sizes are u32, far below usize.
        let hint = size_hint(metadata.size as usize);

        blocks.push((block_hash.0, hint));
    }

    let sapling_roots = sapling_tree_roots(db, span_base, span_last);
    let orchard_roots = orchard_tree_roots(db, span_base, span_last);

    let bytes = chunk_v2::encode(&blocks, true, &sapling_roots, &orchard_roots, true);

    // Cache a complete chunk's generated bytes: regeneration is expensive,
    // and the bytes are a deterministic function of the finalized chain, so
    // caching them is self-verifying. A truncated prefix is never cached, so
    // it can never shadow the complete chunk.
    let expected_last = match pinned_last {
        Some(pinned_last) => span_full_last.min(pinned_last),
        None => span_full_last,
    };
    if span_last == expected_last {
        if let Err(error) = db.write_known_hash_chunk(index, &bytes) {
            warn!(?error, "failed to cache a generated known-hash chunk");
        }
    }

    Some(bytes)
}

/// Quantizes a serialized block `size` into a `chunk_v2` size hint byte.
///
/// The hint `w` means "size is at most `w × SIZE_HINT_UNIT` bytes", so it is
/// always an upper bound. A zero-byte block (which cannot occur) and any size
/// at or below one unit both map to `1`; oversized values saturate at the
/// loosest `DEFAULT_SIZE_HINT` bound.
fn size_hint(size: usize) -> u8 {
    // `size.div_ceil(unit)` is the smallest `w` with `w * unit >= size`.
    // `SIZE_HINT_UNIT` is a small positive constant, so the division is safe.
    let quantized = (size as u64).div_ceil(SIZE_HINT_UNIT as u64).max(1);

    // Saturate at the loosest bound: hints above 255 don't fit in a byte, and
    // `DEFAULT_SIZE_HINT` (255) is the loosest valid upper bound anyway.
    // The cast is safe because the value is clamped to `1..=255` first.
    quantized.min(chunk_v2::DEFAULT_SIZE_HINT as u64) as u8
}

/// Collects the sapling tree-root records for the span
/// `[span_base, span_last]`: the relative height and tree root of each height
/// that appends at least [`TREE_FRONTIER_MIN_NOTES`] notes, in ascending
/// order.
///
/// Heights that update the tree by fewer notes are omitted: the consuming
/// engine folds those blocks' notes itself, and only downloads a frontier
/// where the fold is expensive enough to be worth the artifact bytes (the
/// per-block threshold trade-off is documented on the constant).
fn sapling_tree_roots(db: &ZebraDb, span_base: u32, span_last: u32) -> Vec<TreeRoot> {
    // The baseline note count just below the span, so the first in-span
    // updating height's appended-note delta is correct. `*_tree_by_height`
    // searches at-or-before, covering non-updating baseline heights.
    let baseline = span_base
        .checked_sub(1)
        .and_then(|below| db.sapling_tree_by_height(&Height(below)))
        .map_or(0, |tree| tree.count());

    threshold_tree_roots(
        baseline,
        db.sapling_tree_by_height_range(Height(span_base)..=Height(span_last))
            .map(|(height, tree)| {
                // `height >= span_base` because the range starts at
                // `span_base`, so the subtraction does not underflow.
                (height.0 - span_base, tree.count(), (&tree.root()).into())
            }),
    )
}

/// Collects the orchard tree-root records for the span
/// `[span_base, span_last]`, like [`sapling_tree_roots`].
fn orchard_tree_roots(db: &ZebraDb, span_base: u32, span_last: u32) -> Vec<TreeRoot> {
    let baseline = span_base
        .checked_sub(1)
        .and_then(|below| db.orchard_tree_by_height(&Height(below)))
        .map_or(0, |tree| tree.count());

    threshold_tree_roots(
        baseline,
        db.orchard_tree_by_height_range(Height(span_base)..=Height(span_last))
            .map(|(height, tree)| {
                // `height >= span_base`, as in `sapling_tree_roots`.
                (height.0 - span_base, tree.count(), (&tree.root()).into())
            }),
    )
}

/// Filters `(rel_height, tree note count, root)` records, in ascending height
/// order starting from a tree of `baseline` notes, down to the heights that
/// append at least [`TREE_FRONTIER_MIN_NOTES`] notes.
///
/// The delta at each height is measured against the previous *updating*
/// height's count (not the previous shipped height's), so it is exactly the
/// number of notes the block at that height appended.
fn threshold_tree_roots(
    baseline: u64,
    updates: impl Iterator<Item = (u32, u64, [u8; 32])>,
) -> Vec<TreeRoot> {
    let mut prev_count = baseline;
    let mut roots = Vec::new();

    for (rel_height, count, root) in updates {
        let appended = count.saturating_sub(prev_count);
        prev_count = count;

        if appended >= TREE_FRONTIER_MIN_NOTES {
            roots.push(TreeRoot { rel_height, root });
        }
    }

    roots
}

/// Resolves a content-addressed synchronization artifact by its SHA-256
/// `hash`, for the v2 network protocol's `get-object` serving.
///
/// The serving lookup is built from the compiled constants, never from
/// request-supplied heights: a pinned known-hash chunk hash maps to its
/// chunk index, whose bytes are read from the store or regenerated from
/// state, and the pinned spentness-hint hash maps to the stored artifact at
/// the pinned checkpoint height. A node therefore never computes "spentness
/// as of height H" in response to a request.
///
/// Returns `None` when `hash` is not a pinned artifact of this network, or
/// the artifact is not held (a chunk span entirely in the future, or a
/// spentness hint this node has neither captured nor downloaded yet).
pub fn sync_artifact_bytes(db: &ZebraDb, network: &Network, hash: &[u8; 32]) -> Option<Vec<u8>> {
    if let Some(spec) = KnownHashListSpec::for_network(network) {
        if let Some(index) = spec.chunk_index_by_hash(hash) {
            // The cast is safe: chunk counts are in the tens, far below u32.
            return known_hash_chunk_bytes(db, index as u32);
        }
    }

    if let Some(max_checkpoint) = spentness_hints::max_checkpoint(network) {
        if *hash == max_checkpoint.spentness_hash {
            return db.spentness_hint(max_checkpoint.height);
        }
    }

    None
}

/// Captures the spentness-hint artifact for `max_checkpoint`, stores it in
/// the `spentness_hint` column family, and returns the artifact's content
/// hash.
///
/// The capture is one ordered scan of the finalized UTXO set (already in
/// canonical bit order) against the per-height cumulative transparent output
/// counts: an output that is absent from the set was spent at or below the
/// pinned height, so its hint bit is set; present outputs clear their bits.
///
/// Returns `None` when the finalized tip is not exactly the pinned height —
/// the bitmap records spentness *at that height*, and every later commit
/// changes the UTXO set the scan reads — when the chain's block at the
/// pinned height does not match the pin, or when the sync metadata needed
/// for output ordinals is missing. Nodes whose tip has already passed the
/// pinned height never reconstruct the artifact; they fetch, verify, and
/// store it from peers instead.
///
/// Capture is idempotent: an already-captured artifact returns its hash.
pub fn capture_spentness_hint(
    db: &ZebraDb,
    network: &Network,
    max_checkpoint: &MaxCheckpoint,
) -> Option<[u8; 32]> {
    let height = max_checkpoint.height;

    // An already-captured artifact serves its hash — after re-verifying it
    // against the pin, so a corrupt store is never treated as captured.
    if let Some(bytes) = db.spentness_hint(height) {
        let hints = SpentnessHints::from_bytes(network, bytes).ok()?;
        if max_checkpoint.spentness_hash != [0; 32]
            && hints.artifact_hash() != max_checkpoint.spentness_hash
        {
            warn!(
                ?height,
                "the stored spentness-hint artifact does not match its pinned hash",
            );
            return None;
        }
        return Some(hints.artifact_hash());
    }

    if db.finalized_tip_height()? != height {
        return None;
    }

    // The pin binds the chain: never capture on a chain whose pinned block
    // differs.
    if db.hash(height)? != max_checkpoint.hash {
        return None;
    }

    // The RocksDB iterator reads a consistent view of the UTXO set as of its
    // creation. If the next block commits between the tip check above and
    // the iterator creation, the view is already newer than the pinned
    // height, and the scan would mark outputs spent at the wrong height —
    // so check the tip once more before trusting the view. A commit landing
    // after this check cannot affect the pinned view.
    let utxo_iter = db.utxos_in_canonical_order();
    if db.finalized_tip_height()? != height {
        return None;
    }

    // The cumulative count at the pinned height is the exact number of hint
    // bits, and cross-checks the scan's ordinals.
    let total_outputs = db.sync_metadata(height)?.cumulative_transparent_outputs;

    // The genesis coinbase outputs are unspendable by consensus rule, so
    // Zebra never indexes them in the UTXO set — but they are unspent, and
    // they count toward the ordinals. The scan would mark their bits spent,
    // so they are prepended as present: they occupy the first ordinals,
    // because the ordinal base of every later block is the cumulative count
    // through genesis.
    let genesis_output_count: u64 = {
        let genesis = db.block(Height(0).into())?;
        genesis
            .transactions
            .iter()
            // The cast is a lossless widening: per-transaction output counts
            // are far below u64.
            .map(|tx| tx.outputs().len() as u64)
            .sum()
    };

    let mut present_ordinals: Vec<u64> = (0..genesis_output_count).collect();
    let mut scanned_height: Option<Height> = None;
    let mut ordinal_base: u64 = 0;
    let mut output_prefix: Vec<u64> = Vec::new();

    for (output_location, _output) in utxo_iter {
        let utxo_height = output_location.height();
        if utxo_height > height {
            // Defensive: the tip check above bounds every UTXO's height.
            break;
        }

        if scanned_height != Some(utxo_height) {
            scanned_height = Some(utxo_height);

            ordinal_base = match utxo_height.previous() {
                Ok(previous) => db.sync_metadata(previous)?.cumulative_transparent_outputs,
                // The genesis block starts the ordinal count at zero.
                Err(_) => 0,
            };

            let block = db.block(utxo_height.into())?;
            output_prefix = block
                .transactions
                .iter()
                .scan(0u64, |sum, tx| {
                    let prefix = *sum;
                    // The cast is a lossless widening: per-transaction output
                    // counts are far below u64.
                    *sum += tx.outputs().len() as u64;
                    Some(prefix)
                })
                .collect();
        }

        let ordinal = ordinal_base
            + *output_prefix.get(output_location.transaction_index().as_usize())?
            + u64::from(output_location.output_index().index());

        present_ordinals.push(ordinal);
    }

    let bits = spentness_bits(present_ordinals, total_outputs)?;

    let hints = SpentnessHints::from_bits(network, height, bits);

    // Self-verify against the pin before storing: the artifact is a
    // deterministic function of the chain at the pinned height, so a
    // mismatch means the scan read an inconsistent view. A zero pin hash is
    // an unfilled test pin, which skips the check.
    if max_checkpoint.spentness_hash != [0; 32]
        && hints.artifact_hash() != max_checkpoint.spentness_hash
    {
        warn!(
            ?height,
            "the captured spentness-hint artifact does not match its pinned hash; not storing it",
        );
        return None;
    }

    if let Err(error) = db.write_spentness_hint(height, hints.as_bytes()) {
        warn!(
            ?height,
            ?error,
            "failed to store the captured spentness-hint artifact",
        );
        return None;
    }

    Some(hints.artifact_hash())
}

/// Builds the spentness bitmap bits from the ordinals of the outputs that
/// are present (unspent) in the UTXO set: an output absent from the set was
/// spent at or below the pinned height, so its bit is set, and a present
/// output's bit is clear.
///
/// `present_ordinals` must be in strictly increasing order (the canonical
/// UTXO set order); `total_outputs` is the number of transparent outputs
/// created at or below the pinned height. Returns `None` on an ordinal at or
/// past `total_outputs` or a repeated ordinal — both mean the scan read an
/// inconsistent state.
fn spentness_bits(
    present_ordinals: impl IntoIterator<Item = u64>,
    total_outputs: u64,
) -> Option<Vec<bool>> {
    // `Vec<bool>` is bit-packed, so the in-memory bitmap is the same order
    // of size as the artifact itself.
    let mut bits: Vec<bool> = Vec::new();

    for ordinal in present_ordinals {
        // The casts are lossless widenings: the bitmap length is bounded by
        // the output count, which fits u64.
        if ordinal >= total_outputs || (bits.len() as u64) > ordinal {
            return None;
        }

        // Outputs between the previous present output and this one were
        // spent: their bits are set.
        while (bits.len() as u64) < ordinal {
            bits.push(true);
        }
        bits.push(false);
    }

    // Every output past the last unspent one was spent.
    while (bits.len() as u64) < total_outputs {
        bits.push(true);
    }

    Some(bits)
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use zebra_chain::{
        block::{Block, Height},
        parameters::Network,
        serialization::ZcashDeserializeInto,
    };

    use super::*;
    use crate::{service::finalized_state::FinalizedState, Config};

    use zebra_chain::parameters::known_hashes::chunk_v2::ParsedChunk;

    /// Opens an ephemeral [`FinalizedState`] and commits Mainnet blocks 0..=2.
    fn populated_mainnet_state() -> FinalizedState {
        let network = Network::Mainnet;
        let mut state = FinalizedState::new(
            &Config::ephemeral(),
            &network,
            #[cfg(feature = "elasticsearch")]
            false,
        )
        .expect("opening an ephemeral database should succeed");

        let blocks = network.blockchain_map();
        for height in 0..=2 {
            let block: Arc<Block> = blocks
                .get(&height)
                .expect("block height has test data")
                .zcash_deserialize_into()
                .expect("test data deserializes");

            state
                .commit_finalized_direct(block.into(), None, "known-hash chunk serve test")
                .expect("test block is valid");
        }

        state
    }

    /// The generated chunk for index 0 parses as a valid v2 chunk covering the
    /// finalized prefix of the state's span, with matching block hashes and
    /// non-zero size hints, and generation is deterministic.
    ///
    /// The test state's tip is below `MAX_BLOCK_REORG_HEIGHT`, so the reorg
    /// safety margin truncates the span to height 0 (genesis).
    #[test]
    fn known_hash_chunk_serve_round_trips() {
        let _init_guard = zebra_test::init();

        let state = populated_mainnet_state();
        let db = &state.db;

        let bytes =
            known_hash_chunk_bytes(db, 0).expect("chunk 0 is generated for a populated state");

        let parsed = ParsedChunk::parse(&bytes).expect("generated chunk parses as v2");
        assert_eq!(
            parsed.block_count(),
            1,
            "reorg margin truncates the chunk to the finalized prefix (height 0)"
        );
        assert!(parsed.has_hints(), "generated chunk carries size hints");

        let expected = db
            .hash(Height(0))
            .expect("populated state has the genesis block")
            .0;
        assert_eq!(
            parsed.block_hash(0),
            expected,
            "chunk block hash at rel height 0 matches the state",
        );
        assert_ne!(
            parsed.size_hint(0),
            0,
            "size hint at rel height 0 is a non-zero upper bound",
        );

        // Generation is deterministic: a second call produces identical bytes.
        let bytes_again = known_hash_chunk_bytes(db, 0).expect("chunk 0 regenerates");
        assert_eq!(bytes, bytes_again, "chunk generation is deterministic");
    }

    /// A chunk that has been written into the `known_hash_chunk` column family
    /// is served verbatim from the CF, taking precedence over on-demand
    /// generation.
    #[test]
    fn known_hash_chunk_serve_prefers_stored_cf_bytes() {
        let _init_guard = zebra_test::init();

        let state = populated_mainnet_state();
        let db = &state.db;

        // A sentinel blob that is not a valid generated chunk for index 0.
        let stored: Vec<u8> = vec![0xCD; 16];
        db.write_known_hash_chunk(0, &stored)
            .expect("ephemeral db accepts the write");

        assert_eq!(
            known_hash_chunk_bytes(db, 0).as_deref(),
            Some(stored.as_slice()),
            "stored CF bytes are served verbatim",
        );
    }

    /// A chunk index whose span base is above the last finalized height
    /// returns `None`, rather than an unmatchable empty chunk; an empty state
    /// has no chunks at all.
    #[test]
    fn known_hash_chunk_serve_above_tip_is_none() {
        let _init_guard = zebra_test::init();

        let state = populated_mainnet_state();
        let db = &state.db;

        // Chunk 1's span base (150,000) is far above the test state's tip.
        assert_eq!(
            known_hash_chunk_bytes(db, 1),
            None,
            "chunk index above the finalized span is None",
        );

        let empty_network = Network::Mainnet;
        let empty_state = FinalizedState::new(
            &Config::ephemeral(),
            &empty_network,
            #[cfg(feature = "elasticsearch")]
            false,
        )
        .expect("opening an ephemeral database should succeed");

        assert_eq!(
            known_hash_chunk_bytes(&empty_state.db, 0),
            None,
            "empty state has no chunk to serve",
        );
    }

    /// Capturing at the pinned height stores an artifact whose bits match
    /// every output's spentness, and is idempotent; a pin at the wrong
    /// height or with the wrong block hash captures nothing.
    #[test]
    fn capture_spentness_hint_at_frontier_passage() {
        let _init_guard = zebra_test::init();

        let network = Network::Mainnet;
        let state = populated_mainnet_state();
        let db = &state.db;

        // Every output of blocks 0..=2 is unspent in the test state.
        let total_outputs: u64 = network
            .blockchain_map()
            .range(0..=2)
            .map(|(_, bytes)| {
                let block: Arc<Block> = bytes
                    .zcash_deserialize_into()
                    .expect("test data deserializes");
                // The cast is a lossless widening: output counts are far below u64.
                block
                    .transactions
                    .iter()
                    .map(|tx| tx.outputs().len() as u64)
                    .sum::<u64>()
            })
            .sum();
        assert!(total_outputs > 0, "coinbases always create outputs");

        let block_2_hash = db.hash(Height(2)).expect("populated state has block 2");
        let pin = MaxCheckpoint {
            height: Height(2),
            hash: block_2_hash,
            // Unused by capture: the artifact creates the value this pins.
            spentness_hash: [0; 32],
        };

        // A pin whose block hash does not match the chain captures nothing.
        let wrong_chain_pin = MaxCheckpoint {
            hash: zebra_chain::block::Hash([0xEE; 32]),
            ..pin
        };
        assert_eq!(capture_spentness_hint(db, &network, &wrong_chain_pin), None);

        // A pin below the tip captures nothing: the UTXO set has moved on.
        let stale_pin = MaxCheckpoint {
            height: Height(1),
            hash: db.hash(Height(1)).expect("populated state has block 1"),
            ..pin
        };
        assert_eq!(capture_spentness_hint(db, &network, &stale_pin), None);

        let artifact_hash =
            capture_spentness_hint(db, &network, &pin).expect("capture succeeds at the pinned tip");

        // The stored artifact parses, covers every output, and marks nothing
        // spent.
        let bytes = db
            .spentness_hint(Height(2))
            .expect("captured artifact is stored");
        let hints = SpentnessHints::from_bytes(&network, bytes).expect("stored artifact parses");
        assert_eq!(hints.max_height(), Height(2));
        assert_eq!(hints.output_count(), total_outputs);
        assert_eq!(hints.artifact_hash(), artifact_hash);
        for ordinal in 0..total_outputs {
            assert_eq!(
                hints.is_spent(ordinal),
                Some(false),
                "every test-state output is unspent at ordinal {ordinal}",
            );
        }

        // Idempotent: a second capture returns the same hash.
        assert_eq!(
            capture_spentness_hint(db, &network, &pin),
            Some(artifact_hash),
            "capture is idempotent",
        );
    }

    /// The bitmap builder sets bits for spent (absent) outputs, clears them
    /// for present ones, pads spent bits to the output count, and rejects
    /// out-of-range or repeated ordinals.
    #[test]
    fn spentness_bits_marks_gaps_and_rejects_inconsistency() {
        // Ordinals 1 and 3 of five outputs are unspent.
        let bits = spentness_bits([1, 3], 5).expect("valid ordinals build");
        assert_eq!(bits, vec![true, false, true, false, true]);

        // Every output spent.
        let bits = spentness_bits([], 3).expect("an empty set builds");
        assert_eq!(bits, vec![true, true, true]);

        // Every output unspent.
        let bits = spentness_bits([0, 1, 2], 3).expect("a full set builds");
        assert_eq!(bits, vec![false, false, false]);

        // An ordinal at or past the output count is inconsistent.
        assert_eq!(spentness_bits([3], 3), None);

        // A repeated ordinal is inconsistent.
        assert_eq!(spentness_bits([1, 1], 3), None);
    }
}
