#!/usr/bin/env bash

set -euo pipefail

repository_root="$(git rev-parse --show-toplevel)"
batcher="${repository_root}/.github/scripts/batch-release-changelogs.sh"
temporary_root="$(mktemp -d)"
fixture="${temporary_root}/repository"
releases="${temporary_root}/releases.tsv"

trap 'rm -rf "$temporary_root"' EXIT

if ! command -v changie >/dev/null 2>&1; then
  echo "changie is required to run this test; see https://changie.dev/guide/installation/" >&2
  exit 1
fi

mkdir -p "$fixture"
git -C "$fixture" init --quiet
git -C "$fixture" config user.email release-batcher@example.com
git -C "$fixture" config user.name "Release Batcher"

write_file() {
  local path="$1"
  local content="$2"

  mkdir -p "$(dirname "${fixture}/${path}")"
  printf '%s\n' "$content" > "${fixture}/${path}"
}

commit_fixture() {
  local message="$1"

  git -C "$fixture" add --all
  # --allow-empty: re-running the batcher is expected to be a no-op, and the
  # commit is only here to advance the base revision for the next scenario.
  git -C "$fixture" commit --quiet --allow-empty --message "$message"
}

assert_contains() {
  local path="$1"
  local pattern="$2"

  if ! grep -qF -- "$pattern" "${fixture}/${path}"; then
    echo "expected ${path} to contain: ${pattern}" >&2
    echo "--- ${path}" >&2
    cat "${fixture}/${path}" >&2
    exit 1
  fi
}

# The fixture mirrors Zebra's shape: a binary that depends on a local library,
# and a versionFormat that gives the binary a release link and the library a bare
# version heading.
# shellcheck disable=SC2016 # the versionFormat is a Go template, $p is not a shell variable
write_file .changie.yaml 'changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionExt: md
versionFormat: '"'"'{{ $p := "" }}{{ range .Changes }}{{ $p = .Project }}{{ end }}{{ if eq $p "zebrad" }}## [Zebra {{ .VersionNoPrefix }}](https://example.com/releases/tag/{{ .Version }}){{ else }}## [{{ .VersionNoPrefix }}]{{ end }} - {{ .Time.Format "2006-01-02" }}'"'"'
kindFormat: '"'"'### {{.Kind}}'"'"'
changeFormat: '"'"'- {{.Body}}'"'"'
projectsVersionSeparator: '"'"'-'"'"'
projects:
    - label: zebrad
      key: zebrad
      changelog: CHANGELOG.md
    - label: zebra-example
      key: zebra-example
      changelog: zebra-example/CHANGELOG.md
kinds:
    - key: breaking
      label: Breaking Changes
      auto: major
    - label: Added
      auto: minor
    - label: Changed
      auto: minor
newlines:
    beforeKind: 1
    afterKind: 1
    endOfVersion: 1
    beforeChangelogVersion: 1
envPrefix: CHANGIE_'
write_file .changes/header.tpl.md '# Changelog

All notable changes to this project are documented in this file.'
write_file .changes/zebrad/v1.0.0.md '## [Zebra 1.0.0](https://example.com/releases/tag/v1.0.0) - 2026-07-01

### Added

- The first release.'
write_file .changes/zebra-example/v2.0.0.md '## [2.0.0] - 2026-07-01

### Added

- The first release.'
write_file .changes/unreleased/.gitkeep ''
write_file Cargo.toml '[workspace]
members = ["zebrad", "zebra-example"]'
write_file zebrad/Cargo.toml '[package]
name = "zebrad"
version = "1.0.0"

[dependencies]
zebra-example = { path = "../zebra-example", version = "2.0.0" }'
write_file zebra-example/Cargo.toml '[package]
name = "zebra-example"
version = "2.0.0"'
write_file CHANGELOG.md 'placeholder, regenerated by changie merge'
write_file zebra-example/CHANGELOG.md 'placeholder, regenerated by changie merge'

# A source PR adds a fragment for the library it changed. Nothing declares a
# change to the binary: it is released only because its dependency moves.
write_file .changes/unreleased/zebra-example-breaking-1.yaml 'project: zebra-example
kind: breaking
body: '"'"'Renamed Example::old to Example::new.'"'"''
commit_fixture base

# release-plz bumps the versions and the dependency requirement.
write_file zebra-example/Cargo.toml '[package]
name = "zebra-example"
version = "3.0.0"'
write_file zebrad/Cargo.toml '[package]
name = "zebrad"
version = "1.0.1"

[dependencies]
zebra-example = { path = "../zebra-example", version = "3.0.0" }'
commit_fixture 'chore: release'

printf 'zebra-example\t3.0.0\nzebrad\t1.0.1\n' > "$releases"
(cd "$fixture" && "$batcher" HEAD^ "$releases")

# The library's own entry is batched under its new version.
assert_contains .changes/zebra-example/v3.0.0.md '## [3.0.0]'
assert_contains .changes/zebra-example/v3.0.0.md '### Breaking Changes'
assert_contains .changes/zebra-example/v3.0.0.md '- Renamed Example::old to Example::new.'

# The binary had no fragment, so it gets a dependency entry naming the local
# package release-plz bumped.
assert_contains .changes/zebrad/v1.0.1.md '## [Zebra 1.0.1](https://example.com/releases/tag/v1.0.1)'
assert_contains .changes/zebrad/v1.0.1.md '### Changed'
assert_contains .changes/zebrad/v1.0.1.md '- Updated the following local packages: zebra-example'

# Every changelog is regenerated, newest version first, with the history kept.
assert_contains CHANGELOG.md '## [Zebra 1.0.1](https://example.com/releases/tag/v1.0.1)'
assert_contains CHANGELOG.md '## [Zebra 1.0.0](https://example.com/releases/tag/v1.0.0)'
assert_contains zebra-example/CHANGELOG.md '## [3.0.0]'
assert_contains zebra-example/CHANGELOG.md '## [2.0.0]'

# Fragments are consumed.
if [[ -n "$(find "${fixture}/.changes/unreleased" -name '*.yaml' -print -quit)" ]]; then
  echo "expected the batched fragments to be consumed" >&2
  exit 1
fi

# Re-running after release-plz refreshes the branch must not lose entries or
# duplicate them: the result is a function of the base fragments and the release
# set, so it is byte for byte the same.
cp "${fixture}/CHANGELOG.md" "${temporary_root}/first-changelog.md"
cp "${fixture}/zebra-example/CHANGELOG.md" "${temporary_root}/first-library-changelog.md"
commit_fixture 'chore: batch changelogs'
(cd "$fixture" && "$batcher" HEAD^^ "$releases")
diff -u "${temporary_root}/first-changelog.md" "${fixture}/CHANGELOG.md"
diff -u "${temporary_root}/first-library-changelog.md" "${fixture}/zebra-example/CHANGELOG.md"

# A version already batched on the base revision is left alone.
commit_fixture 'chore: batch changelogs again'
printf 'zebra-example\t3.0.0\n' > "$releases"
(cd "$fixture" && "$batcher" HEAD "$releases")
diff -u "${temporary_root}/first-library-changelog.md" "${fixture}/zebra-example/CHANGELOG.md"

# Releasing a package that has no changie project fails loudly, rather than
# publishing a crate whose changelog cannot be generated.
printf 'zebra-unknown\t1.0.0\n' > "$releases"
if (cd "$fixture" && "$batcher" HEAD "$releases" >/dev/null 2>&1); then
  echo "expected a release of a package with no changie project to fail" >&2
  exit 1
fi

echo "All release changelog batching tests passed."
