#!/usr/bin/env bash

set -euo pipefail

if [[ $# -ne 5 ]]; then
  echo "usage: $0 <base-revision> <head-revision> <conventional> <declared-type> <breaking>" >&2
  exit 2
fi

base_revision="$1"
head_revision="$2"
conventional="$3"
declared_type="$4"
breaking="$5"
repository_root="$(git rev-parse --show-toplevel)"

cd "$repository_root"

# Changelogs are generated by changie, so a PR declares its changes in change
# fragments under this directory, one per (project, change), and never by editing
# a CHANGELOG.md.
unreleased_directory=".changes/unreleased"

# The changie kind that declares a break. This is the kind's *key* from
# `.changie.yaml`, which is what fragments store and what `changie new -k` takes;
# the `Breaking Changes` label is not accepted once a key is set.
breaking_kind="breaking"

allowed_type=false
case "$declared_type" in
  feat|fix|perf|refactor|build|chore|docs|test|ci|style|revert|release)
    allowed_type=true
    ;;
esac

if [[ "$conventional" != "true" || "$allowed_type" != "true" ]]; then
  echo "::error title=Invalid PR title::Add a conventional commit PR title with an allowed type: feat, fix, perf, refactor, build, chore, docs, test, ci, style, revert, or release."
  exit 1
fi

requires_changelog=false
case "$declared_type" in
  feat|fix|perf|refactor|build)
    requires_changelog=true
    ;;
esac

if [[ "$breaking" == "true" ]]; then
  requires_changelog=true
fi

# Reads one top-level scalar field from a fragment, as of the PR head.
fragment_field() {
  local path="$1"
  local field="$2"

  git show "${head_revision}:${path}" | awk -v field="$field" '
    index($0, field ": ") == 1 {
      value = substr($0, length(field) + 3)
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      # Changie quotes bodies that need it; the quotes are not part of the value.
      if (value ~ /^".*"$/ || value ~ /^'"'"'.*'"'"'$/) {
        value = substr(value, 2, length(value) - 2)
      }
      print value
      exit
    }
  '
}

# The fragments this PR adds or edits. Editing an existing fragment counts, the
# same way rewording a bullet used to count.
fragment_paths=()
while IFS= read -r -d '' path; do
  case "$path" in
    "$unreleased_directory"/*.yaml) fragment_paths+=("$path") ;;
  esac
done < <(git diff --name-only -z --diff-filter=AM "$base_revision" "$head_revision" -- "$unreleased_directory")

failed=false
fragment_projects=()
breaking_fragment_projects=()

for path in ${fragment_paths[@]+"${fragment_paths[@]}"}; do
  project="$(fragment_field "$path" project)"
  kind="$(fragment_field "$path" kind)"
  body="$(fragment_field "$path" body)"

  if [[ -z "$project" || -z "$kind" || -z "$body" ]]; then
    printf 'Malformed change fragment: %s\n' "$path" >&2
    echo "::error title=Malformed change fragment::${path} needs a project, a kind and a body. Create fragments with 'changie new' rather than by hand." >&2
    failed=true
    continue
  fi

  # Catches a mistyped project before it reaches the release, where an unknown
  # project silently keeps the entry out of every changelog. Kind keys live in
  # the same file, but no kind key collides with a package name.
  if ! grep -Eq "^[[:space:]]+key: ${project}\$" .changie.yaml; then
    printf 'Unknown project in change fragment: %s declares %s\n' "$path" "$project" >&2
    echo "::error title=Unknown fragment project::${path} declares project '${project}', which is not a project in .changie.yaml." >&2
    failed=true
    continue
  fi

  fragment_projects+=("$project")

  if [[ "$kind" == "$breaking_kind" ]]; then
    breaking_fragment_projects+=("$project")
  fi
done

# A break has to be declared in both places, so the version bump changie derives
# from the fragment and the `semver-checks` skip derived from the title agree.
if [[ "$breaking" != "true" && ${#breaking_fragment_projects[@]} -gt 0 ]]; then
  echo "Breaking fragment without a breaking PR title." >&2
  echo "::error title=Undeclared breaking change::This PR adds a '${breaking_kind}' fragment, so its title needs a conventional commit break marker, for example 'feat!: ...'." >&2
  failed=true
fi

has_fragment_for_project() {
  local wanted="$1"
  local project

  for project in ${fragment_projects[@]+"${fragment_projects[@]}"}; do
    if [[ "$project" == "$wanted" ]]; then
      return 0
    fi
  done

  return 1
}

has_breaking_fragment_for_project() {
  local wanted="$1"
  local project

  for project in ${breaking_fragment_projects[@]+"${breaking_fragment_projects[@]}"}; do
    if [[ "$project" == "$wanted" ]]; then
      return 0
    fi
  done

  return 1
}

package_changed() {
  local package_path="$1"
  local path

  while IFS= read -r -d '' path; do
    # A regenerated changelog is not a change to the package: changie owns that
    # file, and `changie merge` rewrites it from `.changes/`.
    if [[ "$path" == "$package_path/CHANGELOG.md" ]]; then
      continue
    fi

    if [[ "$path" == "$package_path/"* ]]; then
      return 0
    fi
  done < <(git diff --name-only -z "$base_revision" "$head_revision")

  return 1
}

if [[ "$requires_changelog" != "true" ]]; then
  if [[ "$failed" == "true" ]]; then
    exit 1
  fi

  exit 0
fi

zebrad_checked=false
package_metadata="$(
  cargo metadata --no-deps --format-version 1 |
    jq -r '
      .packages[]
      | select(.publish != [])
      | [.name, (.manifest_path | sub("/Cargo.toml$"; ""))]
      | @tsv
    '
)"

while IFS=$'\t' read -r package_name package_directory; do
  if [[ -z "$package_name" ]]; then
    continue
  fi

  package_path="${package_directory#"${repository_root}/"}"

  if [[ "$package_path" == "$package_directory" ]] || ! package_changed "$package_path"; then
    continue
  fi

  # Changie project keys are the package names, so a changed package maps
  # straight onto the `-j` value its fragment must carry.
  if [[ "$package_name" == "zebrad" ]]; then
    zebrad_checked=true
  fi

  if ! has_fragment_for_project "$package_name"; then
    printf 'Missing change fragment for package %s\n' "$package_name" >&2
    echo "::error title=Missing package changelog entry::Each directly changed publishable package needs a change fragment: run 'changie new -j ${package_name}'." >&2
    failed=true
  fi

  if [[ "$breaking" == "true" ]] && ! has_breaking_fragment_for_project "$package_name"; then
    printf 'Missing breaking change fragment for package %s\n' "$package_name" >&2
    echo "::error title=Missing package breaking change fragment::A breaking PR needs a '${breaking_kind}' fragment for each directly changed publishable package: run 'changie new -j ${package_name} -k ${breaking_kind}'." >&2
    failed=true
  fi
done <<< "$package_metadata"

root_manifest_changed=false
while IFS= read -r -d '' path; do
  if [[ "$path" == "Cargo.toml" || "$path" == "Cargo.lock" ]]; then
    root_manifest_changed=true
    break
  fi
done < <(git diff --name-only -z "$base_revision" "$head_revision")

if [[ "$root_manifest_changed" == "true" && "$zebrad_checked" != "true" ]]; then
  if ! has_fragment_for_project zebrad; then
    echo "Root Cargo.toml or Cargo.lock changed without a zebrad change fragment." >&2
    echo "::error title=Missing root changelog entry::Root Cargo.toml or Cargo.lock changes need a zebrad change fragment: run 'changie new -j zebrad'." >&2
    failed=true
  fi

  if [[ "$breaking" == "true" ]] && ! has_breaking_fragment_for_project zebrad; then
    echo "Root Cargo.toml or Cargo.lock changed without a breaking zebrad change fragment." >&2
    echo "::error title=Missing root breaking change fragment::Breaking root Cargo.toml or Cargo.lock changes need a zebrad '${breaking_kind}' fragment: run 'changie new -j zebrad -k ${breaking_kind}'." >&2
    failed=true
  fi
fi

if [[ "$failed" == "true" ]]; then
  exit 1
fi
