#![no_main]

//! Layer-2 jsonrpsee envelope deser fuzz.
//!
//! Sister harness to `rpc_handler_fuzz` (Layer-3 trait dispatch). This
//! one feeds raw JSON-RPC byte strings into
//! `jsonrpsee::RpcModule::raw_json_request(json_str, 1)` so the fuzzer
//! exercises the **envelope** layer:
//!
//!   * `serde_json::from_str::<Request>` — the envelope decoder. This
//!     parses `{"jsonrpc":"2.0","method":"...","params":[...],"id":N}`
//!     into a `jsonrpsee_types::Request`. Attacker-supplied JSON bombs
//!     (deeply-nested arrays, oversized strings, malformed UTF-8) hit
//!     this surface first.
//!   * `Methods::method(method_name)` lookup → MethodNotFound short-
//!     circuit, OR dispatch into `MethodCallback::Async` with raw
//!     `RawValue` params.
//!   * `Params::sequence()` / `Params::parse::<T>()` — the per-method
//!     param decoder generated by `#[rpc(server)]`. This is where
//!     `serde_json` deser of every method's parameter tuple happens
//!     (e.g. `(String, Option<u8>)` for `getblock`). Type confusion,
//!     wrong arity, integer overflow on i32 indices, etc. surface here
//!     **before** the handler body runs — the surface is *upstream* of
//!     what `rpc_handler_fuzz` covers.
//!
//! This harness intentionally drives `raw_json_request` with two input
//! flavours from the libfuzzer-supplied bytes:
//!
//!   1. **Structured envelope** — a small leading byte selects a
//!      method name from the production list, then we synthesize a
//!      JSON-RPC envelope `{"jsonrpc":"2.0","method":"<m>","params":<P>,"id":1}`
//!      where `<P>` is built from the remaining bytes (treated as raw
//!      JSON if it parses, or as a JSON string literal if not). This
//!      drives method-specific `Params::parse` paths.
//!   2. **Raw JSON** — when the leading byte selects "raw", the entire
//!      remaining buffer is handed to `raw_json_request` verbatim.
//!      libFuzzer can then mutate towards arbitrary attacker JSON,
//!      including malformed envelopes, missing fields, oversized
//!      params, batch flooding (jsonrpsee's HTTP layer handles
//!      batches; the `Methods::raw_json_request` API is single-call,
//!      so batches are tested at the HTTP layer in production but
//!      not here — that requires `Server::start` which we deliberately
//!      avoid to keep iterations cheap).
//!
//! All `raw_json_request` calls are wrapped in `panic::catch_unwind`
//! so that a reachable panic from any envelope or param-decoder path
//! is captured as a libFuzzer crash artifact.
//!
//! Build:
//!     cargo +nightly fuzz build jsonrpsee_envelope_fuzz
//!
//! Run (10-min cap):
//!     timeout 660 ./target/x86_64-unknown-linux-gnu/release/jsonrpsee_envelope_fuzz \
//!         -artifact_prefix=fuzz/artifacts/jsonrpsee_envelope_fuzz/ \
//!         -max_total_time=600 -print_final_stats=1 \
//!         fuzz/corpus/jsonrpsee_envelope_fuzz

use std::{
    future,
    panic::{self, AssertUnwindSafe},
    pin::Pin,
    sync::OnceLock,
    task::{Context, Poll},
};

use jsonrpsee::RpcModule;
use libfuzzer_sys::fuzz_target;
use tower::{buffer::Buffer, Service};

use zebra_chain::{
    block, chain_sync_status::ChainSyncStatus, chain_tip::NoChainTip, parameters::Network,
};
use zebra_network::{address_book_peers::AddressBookPeers, types::MetaAddr, PeerSocketAddr};
use zebra_node_services::{mempool, BoxError};
use zebra_rpc::methods::{RpcImpl, RpcServer as _};

// ─────────────────────────────────────────────────────────────────────
// Method name list — every Tier-A/B/C method registered by
// `#[rpc(server)]` on `RpcServer`. These are the strings that
// `raw_json_request` will look up via `Methods::method(name)`. Picking
// from this list (instead of fully arbitrary names) drives the fuzzer
// past the MethodNotFound short-circuit into the per-method
// `Params::parse::<T>` path, which is the actual envelope-deser surface
// we want to exercise.
//
// This list is duplicated from `rpc_handler_fuzz` `RpcCall` plus the
// extra Tier-C methods that don't take fuzzable params (so the Layer-3
// harness skipped them). Any drift between the two lists is acceptable:
// the bench is method-name-driven, not call-arity-driven.
// ─────────────────────────────────────────────────────────────────────

const METHOD_NAMES: &[&str] = &[
    // Tier-A: raw bytes / hex
    "sendrawtransaction",
    "submitblock",
    // Tier-B: addressing
    "getblock",
    "getblockheader",
    "getrawtransaction",
    "gettxout",
    "getbestblockhash",
    "getbestblockheightandhash",
    "getblockcount",
    "getblockhash",
    // Tier-B: address validation
    "validateaddress",
    "z_validateaddress",
    "z_listunifiedreceivers",
    // Tier-B: address index
    "getaddressbalance",
    "getaddresstxids",
    "getaddressutxos",
    // Tier-B: treestate
    "z_gettreestate",
    "z_getsubtreesbyindex",
    // Tier-B: fork manipulation
    "invalidateblock",
    "reconsiderblock",
    // Tier-B: node ops
    "addnode",
    "getpeerinfo",
    "getnetworkinfo",
    "getconnectioncount",
    // Tier-C: subsidy / hashrate
    "getblocksubsidy",
    "getnetworksolps",
    "getnetworkhashps",
    "getmininginfo",
    "getdifficulty",
    // Misc trait methods
    "getinfo",
    "getblockchaininfo",
    "getblocktemplate",
    "getrawmempool",
    "getmempoolinfo",
    "stop",
    "help",
    "ping",
    "z_getnotescount",
    "generate",
    "getacceptedaddrs",
    "estimatefee",
    "getexperimentalfeatures",
];

// ─────────────────────────────────────────────────────────────────────
// Mock services — copied from `rpc_handler_fuzz` (selective-Ok mocks).
//
// The enriched selective-Ok mocks are reused verbatim because they're the
// minimum surface that makes the post-await formatter code reachable
// for every method whose handler awaits state/mempool. For the envelope
// fuzz we don't actually care whether the handler returns Ok or Err —
// we only need the handler to *run* through its `Params::parse` step,
// which happens before the first await. But the Ok mocks let the
// handler proceed further, which catches more panics in formatter and
// post-decode code paths.
// ─────────────────────────────────────────────────────────────────────

struct AlwaysErr<Req, Resp> {
    _phantom: std::marker::PhantomData<fn(Req) -> Resp>,
}

impl<Req, Resp> Clone for AlwaysErr<Req, Resp> {
    fn clone(&self) -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<Req, Resp> AlwaysErr<Req, Resp> {
    fn new() -> Self {
        Self {
            _phantom: std::marker::PhantomData,
        }
    }
}

impl<Req, Resp> Service<Req> for AlwaysErr<Req, Resp>
where
    Req: Send + 'static,
    Resp: Send + 'static,
{
    type Response = Resp;
    type Error = BoxError;
    type Future =
        Pin<Box<dyn future::Future<Output = Result<Resp, BoxError>> + Send + 'static>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, _req: Req) -> Self::Future {
        Box::pin(async { Err::<Resp, BoxError>("fuzz mock: always-err".into()) })
    }
}

#[derive(Clone, Default)]
struct MockReadState;

impl Service<zebra_state::ReadRequest> for MockReadState {
    type Response = zebra_state::ReadResponse;
    type Error = BoxError;
    type Future = Pin<
        Box<
            dyn future::Future<Output = Result<zebra_state::ReadResponse, BoxError>>
                + Send
                + 'static,
        >,
    >;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: zebra_state::ReadRequest) -> Self::Future {
        use zebra_chain::amount::Amount;
        use zebra_state::ReadRequest as R;
        use zebra_state::ReadResponse as Resp;
        let resp: Result<Resp, BoxError> = match req {
            R::Tip => Ok(Resp::Tip(Some((block::Height(0), block::Hash([0u8; 32]))))),
            R::Block(_) => Ok(Resp::Block(None)),
            R::AnyChainBlock(_) => Ok(Resp::Block(None)),
            R::BlockAndSize(_) => Ok(Resp::BlockAndSize(None)),
            R::Transaction(_) => Ok(Resp::Transaction(None)),
            R::AnyChainTransaction(_) => Ok(Resp::AnyChainTransaction(None)),
            R::TransactionIdsForBlock(_) => Ok(Resp::TransactionIdsForBlock(None)),
            R::AnyChainTransactionIdsForBlock(_) => {
                Ok(Resp::AnyChainTransactionIdsForBlock(None))
            }
            R::UnspentBestChainUtxo(_) => Ok(Resp::UnspentBestChainUtxo(None)),
            R::AnyChainUtxo(_) => Ok(Resp::AnyChainUtxo(None)),
            R::Depth(_) => Ok(Resp::Depth(None)),
            R::BlockLocator => Ok(Resp::BlockLocator(Vec::new())),
            R::FindBlockHashes { .. } => Ok(Resp::BlockHashes(Vec::new())),
            R::FindBlockHeaders { .. } => Ok(Resp::BlockHeaders(Vec::new())),
            R::AddressBalance(_) => Ok(Resp::AddressBalance {
                balance: Amount::zero(),
                received: 0,
            }),
            R::TransactionIdsByAddresses { .. } => {
                Ok(Resp::AddressesTransactionIds(Default::default()))
            }
            R::UsageInfo => Ok(Resp::UsageInfo(0)),
            R::SolutionRate { .. } => Ok(Resp::SolutionRate(None)),
            R::TipBlockSize => Ok(Resp::TipBlockSize(None)),
            R::BestChainBlockHash(_) => Ok(Resp::BlockHash(None)),
            R::BlockInfo(_) => Ok(Resp::BlockInfo(None)),
            _ => Err::<Resp, BoxError>("fuzz mock: variant not constructed".into()),
        };
        Box::pin(async move { resp })
    }
}

#[derive(Clone, Default)]
struct MockState;

impl Service<zebra_state::Request> for MockState {
    type Response = zebra_state::Response;
    type Error = BoxError;
    type Future = Pin<
        Box<
            dyn future::Future<Output = Result<zebra_state::Response, BoxError>> + Send + 'static,
        >,
    >;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: zebra_state::Request) -> Self::Future {
        use zebra_state::Request as R;
        use zebra_state::Response as Resp;
        let resp: Result<Resp, BoxError> = match req {
            R::Tip => Ok(Resp::Tip(Some((block::Height(0), block::Hash([0u8; 32]))))),
            R::Block(_) => Ok(Resp::Block(None)),
            R::Transaction(_) => Ok(Resp::Transaction(None)),
            R::Depth(_) => Ok(Resp::Depth(None)),
            R::BlockLocator => Ok(Resp::BlockLocator(Vec::new())),
            R::InvalidateBlock(h) => Ok(Resp::Invalidated(h)),
            R::ReconsiderBlock(_) => Ok(Resp::Reconsidered(Vec::new())),
            _ => Err::<Resp, BoxError>("fuzz mock: variant not constructed".into()),
        };
        Box::pin(async move { resp })
    }
}

#[derive(Clone, Default)]
struct MockMempool;

impl Service<mempool::Request> for MockMempool {
    type Response = mempool::Response;
    type Error = BoxError;
    type Future =
        Pin<Box<dyn future::Future<Output = Result<mempool::Response, BoxError>> + Send + 'static>>;

    fn poll_ready(&mut self, _cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
        Poll::Ready(Ok(()))
    }

    fn call(&mut self, req: mempool::Request) -> Self::Future {
        use mempool::Request as R;
        use mempool::Response as Resp;
        let resp: Result<Resp, BoxError> = match req {
            R::TransactionIds => Ok(Resp::TransactionIds(Default::default())),
            R::TransactionsById(_) | R::TransactionsByMinedId(_) => {
                Ok(Resp::Transactions(Vec::new()))
            }
            R::RejectedTransactionIds(_) => Ok(Resp::RejectedTransactionIds(Default::default())),
            R::CheckForVerifiedTransactions => Ok(Resp::CheckedForVerifiedTransactions),
            R::QueueStats => Ok(Resp::QueueStats {
                size: 0,
                bytes: 0,
                usage: 0,
                fully_notified: None,
            }),
            R::UnspentOutput(_) => Ok(Resp::TransparentOutput(None)),
            _ => Err::<Resp, BoxError>("fuzz mock: variant not constructed".into()),
        };
        Box::pin(async move { resp })
    }
}

#[derive(Clone, Default)]
struct AlwaysSynced;

impl ChainSyncStatus for AlwaysSynced {
    fn is_close_to_tip(&self) -> bool {
        true
    }
}

#[derive(Clone, Default)]
struct EmptyAddressBook;

impl AddressBookPeers for EmptyAddressBook {
    fn recently_live_peers(&self, _now: chrono::DateTime<chrono::Utc>) -> Vec<MetaAddr> {
        Vec::new()
    }

    fn add_peer(&mut self, _peer: PeerSocketAddr) -> bool {
        true
    }
}

type FuzzMempool = MockMempool;
type FuzzState = Buffer<MockState, zebra_state::Request>;
type FuzzReadState = Buffer<MockReadState, zebra_state::ReadRequest>;
type FuzzVerifier = AlwaysErr<zebra_consensus::Request, block::Hash>;

type FuzzRpcImpl = RpcImpl<
    FuzzMempool,
    FuzzState,
    FuzzReadState,
    NoChainTip,
    EmptyAddressBook,
    FuzzVerifier,
    AlwaysSynced,
>;

fn make_rpc(network: Network) -> FuzzRpcImpl {
    let mempool: FuzzMempool = MockMempool;
    let state = Buffer::new(MockState, 1);
    let read_state = Buffer::new(MockReadState, 1);
    let block_verifier_router: FuzzVerifier = AlwaysErr::new();
    let (_log_tx, log_rx) = tokio::sync::watch::channel(None);

    let (rpc, _queue_join) = RpcImpl::new(
        network,
        Default::default(),
        true,
        "0.0.1",
        "jsonrpsee_envelope_fuzz",
        mempool,
        state,
        read_state,
        block_verifier_router,
        AlwaysSynced::default(),
        NoChainTip,
        EmptyAddressBook::default(),
        log_rx,
        None,
    );
    drop(_queue_join);
    rpc
}

// ─────────────────────────────────────────────────────────────────────
// Process-wide singletons.
//
// `RUNTIME` — a multi-threaded tokio runtime. Multi-threaded is needed
// because `RpcImpl::new` calls `tokio::spawn` for the sendrawtransaction
// queue task, and the deeper handler paths spawn additional tasks.
// Single-thread current_thread cannot drive these without manual
// `block_on` discipline, which is fragile across iterations.
//
// `MODULE` — a single `RpcModule<FuzzRpcImpl>` produced by `into_rpc()`.
// The internal `Methods` struct is `Arc<FxHashMap>`, so cloning across
// iterations is `O(1)`. We clone it once per iteration to get a value
// that survives across the async block (the original lives in
// OnceLock<...> and `&'static` references work fine but cloning gives
// the future a 'static lifetime trivially).
// ─────────────────────────────────────────────────────────────────────

fn runtime() -> &'static tokio::runtime::Runtime {
    static RUNTIME: OnceLock<tokio::runtime::Runtime> = OnceLock::new();
    RUNTIME.get_or_init(|| {
        tokio::runtime::Builder::new_multi_thread()
            .worker_threads(2)
            .enable_all()
            .build()
            .expect("fuzz runtime must build (process-wide singleton)")
    })
}

fn module() -> &'static RpcModule<FuzzRpcImpl> {
    static MODULE: OnceLock<RpcModule<FuzzRpcImpl>> = OnceLock::new();
    MODULE.get_or_init(|| {
        // Build the rpc inside the runtime so `tokio::spawn` for the queue
        // worker has a runtime to attach to. We do this by entering the
        // runtime context for the duration of `make_rpc`.
        let _guard = runtime().enter();
        let rpc = make_rpc(Network::Mainnet);
        rpc.into_rpc()
    })
}

// ─────────────────────────────────────────────────────────────────────
// Envelope synthesis from libfuzzer bytes.
//
// Wire format:
//   data[0]            : flavour selector
//                          bit 7 (0x80): raw mode — pass remainder verbatim
//                          else        : structured mode — synthesize envelope
//   data[1] (struct.)  : method index (mod METHOD_NAMES.len())
//   data[2..] (struct.): params bytes
//
// In structured mode we attempt three params encodings, picked by
// data[1] >> 6:
//   00: params bytes interpreted as raw JSON (parse-or-string-fallback)
//   01: params wrapped as a JSON array of one string literal of the bytes
//   10: params wrapped as a JSON array of one number (8-byte big-endian)
//   11: params built from raw bytes as the JSON array body verbatim
//
// All four encodings produce a syntactically valid `params` JSON value
// (or fall back to `[]` if the encoding fails), so the envelope itself
// is always a parseable JSON object — the fuzzer's mutation pressure
// then targets the per-method `Params::parse::<T>` decoder.
//
// Note: id is fixed at 1 (number) to keep envelope parsing
// deterministic. The fuzzer can still drive the `id` decoder via the
// raw-mode flavour if it learns the structure.
// ─────────────────────────────────────────────────────────────────────

fn build_envelope(data: &[u8]) -> Option<String> {
    if data.len() < 2 {
        return None;
    }
    let method_idx = (data[1] as usize) % METHOD_NAMES.len();
    let method = METHOD_NAMES[method_idx];
    let params_kind = data[1] >> 6;
    let payload = &data[2..];

    let params_json = match params_kind {
        0b00 => {
            // Try to interpret as raw JSON; fall back to string literal.
            match std::str::from_utf8(payload) {
                Ok(s) if serde_json::from_str::<serde_json::Value>(s).is_ok() => s.to_string(),
                Ok(s) => format!("[{}]", serde_json::Value::String(s.to_string())),
                Err(_) => "[]".to_string(),
            }
        }
        0b01 => {
            let s = String::from_utf8_lossy(payload).into_owned();
            format!("[{}]", serde_json::Value::String(s))
        }
        0b10 => {
            // Numeric param: 8-byte BE → i64 then JSON number. Wider
            // surface for handlers that take Option<i32> / Option<u32>
            // (getblockhash, getnetworksolps, etc.).
            let mut buf = [0u8; 8];
            for (i, b) in payload.iter().take(8).enumerate() {
                buf[i] = *b;
            }
            let n = i64::from_be_bytes(buf);
            format!("[{}]", n)
        }
        _ => {
            // ── Per-method schema-aware param template.
            //
            // Previously this slot was "raw bytes verbatim" which produces
            // a syntactically-invalid params body 99% of the time and
            // dies at envelope-level `serde_json::from_str::<Request>`
            // instead of reaching the per-method `Params::parse::<T>`
            // surface. By selecting a template based on the method name,
            // we hand `Params::parse` a *type-shaped* body so the
            // per-method decoder runs — that's the actual surface where
            // per-method input-parsing panics live.
            //
            // The remaining fuzz bytes feed the template fields, so
            // libFuzzer can mutate around the type shape (e.g. flip a
            // bool, twiddle a number, lengthen a hex string) and reach
            // both the success path and the per-field rejection paths.
            build_method_param_template(method, payload)
        }
    };

    Some(format!(
        r#"{{"jsonrpc":"2.0","method":"{}","params":{},"id":1}}"#,
        method, params_json
    ))
}

/// Build a positional `params` JSON array tailored to the method's
/// expected signature, fed by fuzz bytes.
///
/// Falls back to `[]` if the byte budget is insufficient. The shapes
/// mirror `RpcServer` trait method signatures in `zebra-rpc/src/methods.rs`:
///
///   sendrawtransaction(hex: String, allow_high_fees: Option<bool>)
///   getblock(hash_or_height: String, verbosity: Option<u8>)
///   getblockheader(hash_or_height: String, verbose: Option<bool>)
///   getrawtransaction(txid: String, verbose: Option<u8>, block_hash: Option<String>)
///   gettxout(txid: String, n: u32, include_mempool: Option<bool>)
///   validateaddress(address: String)
///   z_validateaddress(address: String)
///   z_listunifiedreceivers(address: String)
///   getaddressbalance(req: GetAddressBalanceRequest)  // {"addresses":[...]}
///   getaddresstxids(req: GetAddressTxIdsRequest)      // {"addresses":[...], "start":N, "end":N}
///   getaddressutxos(req: GetAddressUtxosRequest)      // {"addresses":[...]} OR {"chainInfo": false, "addresses":[...]}
///   z_gettreestate(hash_or_height: String)
///   z_getsubtreesbyindex(pool: String, start_index: u16, limit: Option<u16>)
///   invalidateblock(block_hash: String)
///   reconsiderblock(block_hash: String)
///   addnode(addr: PeerSocketAddr, command: AddNodeCommand)  // ["host:port", "add"]
///   getblockhash(index: i32)
///   getblocksubsidy(height: Option<u32>)
///   getnetworksolps(num_blocks: Option<i32>, height: Option<i32>)
///   getnetworkhashps(num_blocks: Option<i32>, height: Option<i32>)
///   getrawmempool(verbose: Option<bool>)
///   submitblock(hex: HexData, _: Option<SubmitBlockParameters>)  // ["DEADBEEF"]
fn build_method_param_template(method: &str, payload: &[u8]) -> String {
    // Helper closures that pull bytes safely.
    let take_u8 = |i: usize| payload.get(i).copied().unwrap_or(0);
    let take_u32_le = |off: usize| {
        if payload.len() >= off + 4 {
            let mut b = [0u8; 4];
            b.copy_from_slice(&payload[off..off + 4]);
            u32::from_le_bytes(b)
        } else {
            0
        }
    };
    let take_i32_le = |off: usize| take_u32_le(off) as i32;
    // Hex string from bytes (truncated). The leading byte sets the length
    // class so the fuzzer can target both 32-byte (hash-shaped) and
    // tx-byte-shaped payloads.
    let hex_class = |class: u8, src: &[u8]| -> String {
        let len_target = match class & 0x03 {
            0 => 64,                              // 32-byte hash
            1 => 40,                              // 20-byte address-ish
            2 => src.len().min(64).max(2),       // arbitrary
            _ => src.len().min(2048).max(0),     // tx-byte sized hex
        };
        let raw = if src.len() >= len_target / 2 {
            &src[..len_target / 2]
        } else {
            src
        };
        hex::encode(raw)
    };

    match method {
        "sendrawtransaction" => {
            // [hex_string, optional bool]
            let hex_tx = hex_class(take_u8(0), &payload[1.min(payload.len())..]);
            let allow = (take_u8(0) >> 4) & 0x1 == 1;
            format!(
                r#"["{}",{}]"#,
                hex_tx,
                if allow { "true" } else { "false" }
            )
        }
        "submitblock" => {
            // [hex_string]
            let hex_blob = hex_class(0x80, &payload[1.min(payload.len())..]);
            format!(r#"["{}"]"#, hex_blob)
        }
        "getblock" | "getblockheader" | "z_gettreestate" => {
            // [hash_or_height_str, optional verbosity]
            // The leading byte chooses string-form: hash hex (64 chars) vs
            // numeric height vs raw JSON-string fuzz bytes.
            let s = match take_u8(0) & 0x3 {
                0 => hex_class(0, &payload[1.min(payload.len())..]),
                1 => format!("{}", take_u32_le(1) % 4_000_000),
                _ => String::from_utf8_lossy(&payload[1.min(payload.len())..32.min(payload.len())])
                    .into_owned()
                    .replace('"', ""),
            };
            let verb = (take_u8(0) >> 2) & 0x7;
            if method == "getblockheader" {
                format!(r#"["{}",{}]"#, s, verb % 2 == 1)
            } else {
                format!(r#"["{}",{}]"#, s, verb)
            }
        }
        "getrawtransaction" => {
            // [txid_hex, verbose, optional block_hash_hex]
            let txid = hex_class(0, &payload[1.min(payload.len())..]);
            let verb = (take_u8(0) >> 2) & 0x3;
            let block_hash = hex_class(0, &payload[33.min(payload.len())..]);
            format!(r#"["{}",{},"{}"]"#, txid, verb, block_hash)
        }
        "gettxout" => {
            // [txid_hex, u32 vout, optional bool include_mempool]
            let txid = hex_class(0, &payload[1.min(payload.len())..]);
            let n = take_u32_le(1) % 100;
            let include = (take_u8(0) >> 4) & 0x1 == 1;
            format!(r#"["{}",{},{}]"#, txid, n, include)
        }
        "validateaddress" | "z_validateaddress" | "z_listunifiedreceivers" => {
            // [addr_string]
            let s = String::from_utf8_lossy(&payload[..payload.len().min(96)])
                .into_owned()
                .replace('"', "");
            format!(r#"["{}"]"#, s)
        }
        "getaddressbalance" => {
            // The DTO is two-form via `from = "DGetAddressBalanceRequest"` —
            // either {"addresses":[...]} or {"address":"..."} (singular).
            // We feed the {"addresses":[...]} form so the longer parse path
            // runs.
            let addr1 = String::from_utf8_lossy(&payload[..payload.len().min(48)])
                .into_owned()
                .replace('"', "");
            format!(r#"[{{"addresses":["{}"]}}]"#, addr1)
        }
        "getaddresstxids" => {
            // {"addresses":[...], "start":N, "end":N}
            let addr1 = String::from_utf8_lossy(&payload[..payload.len().min(48)])
                .into_owned()
                .replace('"', "");
            let start = take_u32_le(50.min(payload.len()));
            let end = take_u32_le(54.min(payload.len()));
            format!(
                r#"[{{"addresses":["{}"],"start":{},"end":{}}}]"#,
                addr1, start, end
            )
        }
        "getaddressutxos" => {
            // {"addresses":[...], "chainInfo":bool}
            let addr1 = String::from_utf8_lossy(&payload[..payload.len().min(48)])
                .into_owned()
                .replace('"', "");
            let ci = take_u8(0) & 0x1 == 1;
            format!(
                r#"[{{"addresses":["{}"],"chainInfo":{}}}]"#,
                addr1, ci
            )
        }
        "z_getsubtreesbyindex" => {
            // [pool_str, u16 start, optional u16 limit]
            let pool = match take_u8(0) & 0x3 {
                0 => "sapling",
                1 => "orchard",
                2 => "sprout",
                _ => "deferred",
            };
            let start = take_u32_le(1) as u16;
            let limit = take_u32_le(5) as u16;
            format!(r#"["{}",{},{}]"#, pool, start, limit)
        }
        "invalidateblock" | "reconsiderblock" => {
            // [block_hash_hex]
            let s = hex_class(0, &payload[1.min(payload.len())..]);
            format!(r#"["{}"]"#, s)
        }
        "addnode" => {
            // [addr_str, command_str]
            // Real addrs look like "127.0.0.1:8233". Fuzz drives via the
            // parser; we put a real-shaped address with mutated port.
            let port = take_u32_le(0) % 65536;
            let cmd = match take_u8(4) & 0x1 {
                0 => "add",
                _ => "remove",
            };
            format!(r#"["127.0.0.1:{}","{}"]"#, port, cmd)
        }
        "getblockhash" => {
            // [i32 index]
            format!(r#"[{}]"#, take_i32_le(0))
        }
        "getblocksubsidy" => {
            // [optional u32 height]
            format!(r#"[{}]"#, take_u32_le(0))
        }
        "getnetworksolps" | "getnetworkhashps" => {
            // [optional i32 num_blocks, optional i32 height]
            format!(r#"[{},{}]"#, take_i32_le(0), take_i32_le(4))
        }
        "getrawmempool" => {
            // [optional bool verbose]
            let v = take_u8(0) & 0x1 == 1;
            format!(r#"[{}]"#, v)
        }
        "generate" => {
            // [u32 num_blocks]
            format!(r#"[{}]"#, take_u32_le(0) % 64)
        }
        // No-arg methods. `[]` keeps the envelope parseable.
        "getinfo" | "getblockchaininfo" | "getbestblockhash"
        | "getbestblockheightandhash" | "getblockcount" | "getmempoolinfo"
        | "getmininginfo" | "getdifficulty" | "getnetworkinfo" | "getpeerinfo"
        | "getconnectioncount" | "stop" | "ping" | "z_getnotescount"
        | "getacceptedaddrs" | "estimatefee" | "getexperimentalfeatures"
        | "help" => "[]".to_string(),
        // For methods we don't have a template for, fall back to the raw-
        // body strategy (often produces invalid JSON, exercising envelope
        // parser rejection).
        _ => {
            let body = String::from_utf8_lossy(payload).into_owned();
            format!("[{}]", body)
        }
    }
}

// ─────────────────────────────────────────────────────────────────────
// Fuzz entry point.
// ─────────────────────────────────────────────────────────────────────

fuzz_target!(|data: &[u8]| {
    if data.is_empty() {
        return;
    }
    let flavour = data[0];

    // Build the request string. Two flavours:
    //   bit 7 set → raw mode, pass remainder verbatim (or empty if empty)
    //   else      → structured mode
    let request_str = if flavour & 0x80 != 0 {
        match std::str::from_utf8(&data[1..]) {
            Ok(s) => s.to_string(),
            Err(_) => return, // can't pass non-utf8 to raw_json_request
        }
    } else {
        match build_envelope(data) {
            Some(s) => s,
            None => return,
        }
    };

    // Cap request length to prevent runaway memory in pathological
    // inputs. The production server caps at 2*MAX_BLOCK_BYTES + 1024
    // (~4 MiB); we cap lower here because our purpose is to find
    // panics in the deser surface, not memory pressure (libFuzzer has
    // its own RSS limit).
    if request_str.len() > 256 * 1024 {
        return;
    }

    let module = module();
    let runtime = runtime();

    let _ = panic::catch_unwind(AssertUnwindSafe(|| {
        runtime.block_on(async {
            let _ = module.raw_json_request(&request_str, 1).await;
        });
    }));
});
