{
 "title": "checkpoint verification",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(sync_prospective_tips_len, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Checkpoint Height - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "checkpoint_processing_next_height{job=\"$job\"}",
     "legendFormat": "next_check"
    },
    {
     "expr": "checkpoint_queued_continuous_height{job=\"$job\"}",
     "legendFormat": "queue_cont"
    },
    {
     "expr": "checkpoint_verified_height{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "queue_max"
    },
    {
     "expr": "state_checkpoint_committed_block_height{job=\"$job\"}",
     "legendFormat": "state_commit"
    },
    {
     "expr": "state_checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "state_q_max"
    }
   ]
  },
  {
   "title": "Checkpoint Height - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "checkpoint_processing_next_height{job=\"$job\"}",
     "legendFormat": "next_check"
    },
    {
     "expr": "checkpoint_queued_continuous_height{job=\"$job\"}",
     "legendFormat": "queue_cont"
    },
    {
     "expr": "checkpoint_verified_height{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "queue_max"
    },
    {
     "expr": "state_checkpoint_committed_block_height{job=\"$job\"}",
     "legendFormat": "state_commit"
    },
    {
     "expr": "state_checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "state_q_max"
    }
   ]
  },
  {
   "title": "Checkpoint Height - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "checkpoint_processing_next_height{job=\"$job\"}",
     "legendFormat": "next_check"
    },
    {
     "expr": "checkpoint_queued_continuous_height{job=\"$job\"}",
     "legendFormat": "queue_cont"
    },
    {
     "expr": "checkpoint_verified_height{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "queue_max"
    },
    {
     "expr": "state_checkpoint_committed_block_height{job=\"$job\"}",
     "legendFormat": "state_commit"
    },
    {
     "expr": "state_checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "state_q_max"
    }
   ]
  },
  {
   "title": "Checkpoint Height - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "checkpoint_processing_next_height{job=\"$job\"}",
     "legendFormat": "next_check"
    },
    {
     "expr": "checkpoint_queued_continuous_height{job=\"$job\"}",
     "legendFormat": "queue_cont"
    },
    {
     "expr": "checkpoint_verified_height{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "queue_max"
    },
    {
     "expr": "state_checkpoint_committed_block_height{job=\"$job\"}",
     "legendFormat": "state_commit"
    },
    {
     "expr": "state_checkpoint_queued_max_height{job=\"$job\"}",
     "legendFormat": "state_q_max"
    }
   ]
  },
  {
   "title": "Checkpoint Pipeline Throughput - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(checkpoint_verified_block_count[1s])",
     "legendFormat": "checkpoint verify rate [1s]"
    },
    {
     "expr": "rate(state_checkpoint_committed_block_count[1s])",
     "legendFormat": "state commit rate [1s]"
    },
    {
     "expr": "rate(sync_downloaded_block_count[1s])",
     "legendFormat": "sync download rate [1s]"
    },
    {
     "expr": "rate(gossip_downloaded_block_count[1s])",
     "legendFormat": "gossip download rate [1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Pipeline Throughput - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(checkpoint_verified_block_count[1s])",
     "legendFormat": "checkpoint verify rate [1s]"
    },
    {
     "expr": "rate(state_checkpoint_committed_block_count[1s])",
     "legendFormat": "state commit rate [1s]"
    },
    {
     "expr": "rate(sync_downloaded_block_count[1s])",
     "legendFormat": "sync download rate [1s]"
    },
    {
     "expr": "rate(gossip_downloaded_block_count[1s])",
     "legendFormat": "gossip download rate [1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Pipeline Throughput - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(checkpoint_verified_block_count[1s])",
     "legendFormat": "checkpoint verify rate [1s]"
    },
    {
     "expr": "rate(state_checkpoint_committed_block_count[1s])",
     "legendFormat": "state commit rate [1s]"
    },
    {
     "expr": "rate(sync_downloaded_block_count[1s])",
     "legendFormat": "sync download rate [1s]"
    },
    {
     "expr": "rate(gossip_downloaded_block_count[1s])",
     "legendFormat": "gossip download rate [1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Pipeline Throughput - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(checkpoint_verified_block_count[1s])",
     "legendFormat": "checkpoint verify rate [1s]"
    },
    {
     "expr": "rate(state_checkpoint_committed_block_count[1s])",
     "legendFormat": "state commit rate [1s]"
    },
    {
     "expr": "rate(sync_downloaded_block_count[1s])",
     "legendFormat": "sync download rate [1s]"
    },
    {
     "expr": "rate(gossip_downloaded_block_count[1s])",
     "legendFormat": "gossip download rate [1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Queues - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "checkpoint_queued_slots{job=\"$job\"}",
     "legendFormat": "checkpoint_queued_slots"
    },
    {
     "expr": "state_checkpoint_queued_block_count{job=\"$job\"}",
     "legendFormat": "state_finalized_queued_block_count"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "sync_prospective_tips_len"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "sync_downloads_in_flight"
    },
    {
     "expr": "sync_pending_blocks_len{job=\"$job\"}",
     "legendFormat": "sync_pending_blocks_len"
    },
    {
     "expr": "rate(sync_cancelled_download_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_download_count[1s]"
    },
    {
     "expr": "rate(sync_cancelled_verify_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_verify_count[1s]"
    },
    {
     "expr": "rate(gossip_queued_block_count{job=\"$job\"}[1s])",
     "legendFormat": "gossip_queued_block_count[1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Queues - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "checkpoint_queued_slots{job=\"$job\"}",
     "legendFormat": "checkpoint_queued_slots"
    },
    {
     "expr": "state_checkpoint_queued_block_count{job=\"$job\"}",
     "legendFormat": "state_finalized_queued_block_count"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "sync_prospective_tips_len"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "sync_downloads_in_flight"
    },
    {
     "expr": "sync_pending_blocks_len{job=\"$job\"}",
     "legendFormat": "sync_pending_blocks_len"
    },
    {
     "expr": "rate(sync_cancelled_download_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_download_count[1s]"
    },
    {
     "expr": "rate(sync_cancelled_verify_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_verify_count[1s]"
    },
    {
     "expr": "rate(gossip_queued_block_count{job=\"$job\"}[1s])",
     "legendFormat": "gossip_queued_block_count[1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Queues - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "checkpoint_queued_slots{job=\"$job\"}",
     "legendFormat": "checkpoint_queued_slots"
    },
    {
     "expr": "state_checkpoint_queued_block_count{job=\"$job\"}",
     "legendFormat": "state_finalized_queued_block_count"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "sync_prospective_tips_len"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "sync_downloads_in_flight"
    },
    {
     "expr": "sync_pending_blocks_len{job=\"$job\"}",
     "legendFormat": "sync_pending_blocks_len"
    },
    {
     "expr": "rate(sync_cancelled_download_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_download_count[1s]"
    },
    {
     "expr": "rate(sync_cancelled_verify_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_verify_count[1s]"
    },
    {
     "expr": "rate(gossip_queued_block_count{job=\"$job\"}[1s])",
     "legendFormat": "gossip_queued_block_count[1s]"
    }
   ]
  },
  {
   "title": "Checkpoint Queues - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "checkpoint_queued_slots{job=\"$job\"}",
     "legendFormat": "checkpoint_queued_slots"
    },
    {
     "expr": "state_checkpoint_queued_block_count{job=\"$job\"}",
     "legendFormat": "state_finalized_queued_block_count"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "sync_prospective_tips_len"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "sync_downloads_in_flight"
    },
    {
     "expr": "sync_pending_blocks_len{job=\"$job\"}",
     "legendFormat": "sync_pending_blocks_len"
    },
    {
     "expr": "rate(sync_cancelled_download_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_download_count[1s]"
    },
    {
     "expr": "rate(sync_cancelled_verify_count{job=\"$job\"}[1s])",
     "legendFormat": "sync_cancelled_verify_count[1s]"
    },
    {
     "expr": "rate(gossip_queued_block_count{job=\"$job\"}[1s])",
     "legendFormat": "gossip_queued_block_count[1s]"
    }
   ]
  }
 ]
}