{
 "title": "peers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(zcash_net_in_bytes_total, job)"
    }
   },
   {
    "name": "seed",
    "query": {
     "query": "label_values(zcash_net_peers_initial, seed)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Compatible Seed Peers - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (remote_version, seed) (label_replace(zcash_net_peers_initial{job=\"$job\",seed=~\"$seed\"}, \"seed\", \"$1\", \"seed\", \"(.*):1?8233\") * on(remote_ip) group_left(remote_version) (count_values by (remote_ip) (\"remote_version\", zcash_net_peers_version_connected{job=\"$job\"})))",
     "legendFormat": "{{remote_version}} - {{seed}}"
    }
   ]
  },
  {
   "title": "Obsolete Seed Peers - $job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (remote_version, seed) (label_replace(zcash_net_peers_initial{job=\"$job\",seed=~\"$seed\"}, \"seed\", \"$1\", \"seed\", \"(.*):1?8233\") * on(remote_ip) group_left(remote_version) (count_values by (remote_ip) (\"remote_version\", zcash_net_peers_version_obsolete{job=\"$job\"})))",
     "legendFormat": "{{remote_version}} - {{seed}}"
    }
   ]
  },
  {
   "title": "Compatible Peers - $job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (remote_version) (zcash_net_peers_connected{job=\"$job\"})",
     "legendFormat": "{{remote_version}}"
    }
   ]
  },
  {
   "title": "Obsolete Peers - $job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (remote_version) (zcash_net_peers_obsolete{job=\"$job\"})",
     "legendFormat": "{{remote_version}}"
    }
   ]
  },
  {
   "title": "Peer User Agents - $job",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (user_agent) (zcash_net_peers_connected{job=\"$job\"})",
     "legendFormat": "{{user_agent}}"
    }
   ]
  }
 ]
}