{
 "title": "Syncer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(zcash_net_in_bytes_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Queued Downloads  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_obtain_queued_hash_count{job=\"$job\"}",
     "legendFormat": "obtain tips"
    },
    {
     "expr": "sync_extend_queued_hash_count{job=\"$job\"}",
     "legendFormat": "extend tips"
    }
   ]
  },
  {
   "title": "Sync Queued Downloads  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_obtain_queued_hash_count{job=\"$job\"}",
     "legendFormat": "obtain tips"
    },
    {
     "expr": "sync_extend_queued_hash_count{job=\"$job\"}",
     "legendFormat": "extend tips"
    }
   ]
  },
  {
   "title": "Sync Peer Responses  - $job",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "job",
   "targets": [
    {
     "expr": "sync_obtain_response_hash_count{job=\"$job\"}",
     "legendFormat": "obtain tips"
    },
    {
     "expr": "sync_extend_response_hash_count{job=\"$job\"}",
     "legendFormat": "extend tips"
    }
   ]
  },
  {
   "title": "Sync Peer Responses  - $job",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sync_obtain_response_hash_count{job=\"$job\"}",
     "legendFormat": "obtain tips"
    },
    {
     "expr": "sync_extend_response_hash_count{job=\"$job\"}",
     "legendFormat": "extend tips"
    }
   ]
  },
  {
   "title": "Sync Status  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_cancelled_download_count{job=\"$job\"}",
     "legendFormat": "cancelled downloads"
    },
    {
     "expr": "sync_cancelled_verify_count{job=\"$job\"}",
     "legendFormat": "cancelled verifications"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "in-flight downloads"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "prospective tips"
    },
    {
     "expr": "sync_downloaded_block_count{job=\"$job\"}",
     "legendFormat": "downloaded blocks"
    },
    {
     "expr": "sync_verified_block_count{job=\"$job\"}",
     "legendFormat": "verified blocks"
    }
   ]
  },
  {
   "title": "Sync Status  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sync_cancelled_download_count{job=\"$job\"}",
     "legendFormat": "cancelled downloads"
    },
    {
     "expr": "sync_cancelled_verify_count{job=\"$job\"}",
     "legendFormat": "cancelled verifications"
    },
    {
     "expr": "sync_downloads_in_flight{job=\"$job\"}",
     "legendFormat": "in-flight downloads"
    },
    {
     "expr": "sync_prospective_tips_len{job=\"$job\"}",
     "legendFormat": "prospective tips"
    },
    {
     "expr": "sync_downloaded_block_count{job=\"$job\"}",
     "legendFormat": "downloaded blocks"
    },
    {
     "expr": "sync_verified_block_count{job=\"$job\"}",
     "legendFormat": "verified blocks"
    }
   ]
  }
 ]
}