{
 "title": "🔎",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zcash_chain_verified_block_height{}"
    }
   ]
  },
  {
   "title": "Signatures validated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(signatures_redjubjub_validated{}[$__interval])",
     "legendFormat": "RedJubjub"
    },
    {
     "expr": "rate(signatures_ed25519_validated{}[$__interval])",
     "legendFormat": "Ed25519"
    }
   ]
  },
  {
   "title": "Transactions finalized",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(state_finalized_cumulative_transactions{}[$__interval])",
     "legendFormat": "Transactions finalized"
    }
   ]
  },
  {
   "title": "Proofs verified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(proofs_groth16_verified{}[$__interval])",
     "legendFormat": "Groth16"
    }
   ]
  },
  {
   "title": "Transparent Outpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(state_finalized_cumulative_transparent_newouts{}[$__interval])",
     "legendFormat": "Transparent newOuts"
    },
    {
     "expr": "rate(state_finalized_cumulative_transparent_prevouts{}[$__interval])",
     "legendFormat": "Transparent prevOuts"
    }
   ]
  },
  {
   "title": "Nullifiers revealed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(state_finalized_cumulative_sapling_nullifiers{}[$__interval])",
     "legendFormat": "Sapling"
    },
    {
     "expr": "rate(state_finalized_cumulative_orchard_nullifiers{}[$__interval])",
     "legendFormat": "Orchard"
    },
    {
     "expr": "rate(state_finalized_cumulative_sprout_nullifiers{}[$__interval])",
     "legendFormat": "Sprout"
    }
   ]
  }
 ]
}