FROM rustlang/rust:nightly

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	make cmake g++ gcc llvm libclang-dev

RUN mkdir /zebra
WORKDIR /zebra

ENV RUST_BACKTRACE 1
ENV CARGO_HOME /zebra/.cargo/

RUN rustc -V; cargo -V; rustup -V

EXPOSE 8233 18233

COPY . .

# Filtering to only run integration tests requires nightly for now
CMD cargo +nightly test --all --test '*' --no-fail-fast -- -Zunstable-options --include-ignored
