{
 "title": "mempool",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(zcash_net_in_bytes_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mempool Storage  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "zcash_mempool_size_transactions{job=\"$job\"}",
     "legendFormat": "transactions"
    },
    {
     "expr": "zcash_mempool_size_bytes{job=\"$job\"}",
     "legendFormat": " serialized bytes"
    },
    {
     "expr": "mempool_currently_queued_transactions{job=\"$job\"}",
     "legendFormat": "queued transactions"
    }
   ]
  },
  {
   "title": "Mempool Rejected Storage  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mempool_rejected_transaction_ids{job=\"$job\"}",
     "legendFormat": "rejected transactions"
    },
    {
     "expr": "mempool_rejected_transaction_ids_bytes{job=\"$job\"}",
     "legendFormat": "rejected serialized bytes"
    }
   ]
  },
  {
   "title": "Block Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sync_downloaded_block_count{job=\"$job\"}[1m])",
     "legendFormat": "sync download"
    },
    {
     "expr": "rate(zcash_chain_verified_block_total{job=\"$job\"}[1m])",
     "legendFormat": "state commit"
    }
   ]
  },
  {
   "title": "Transaction Downloader and Verifier, Gossiper  - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mempool_queued_transactions_total{job=\"$job\"}",
     "legendFormat": "queued"
    },
    {
     "expr": "mempool_downloaded_transactions_total{job=\"$job\"}",
     "legendFormat": "downloaded"
    },
    {
     "expr": "mempool_pushed_transactions_total{job=\"$job\"}",
     "legendFormat": "pushed"
    },
    {
     "expr": "mempool_verified_transactions_total{job=\"$job\"}",
     "legendFormat": "verified"
    },
    {
     "expr": "mempool_cancelled_verify_tasks_total{job=\"$job\"}",
     "legendFormat": "cancelled"
    },
    {
     "expr": "mempool_failed_verify_tasks_total{job=\"$job\"}",
     "legendFormat": "failed - {{reason}}"
    },
    {
     "expr": "mempool_gossiped_transactions_total{job=\"$job\"}",
     "legendFormat": "gossiped"
    }
   ]
  },
  {
   "title": "Transaction Downloader and Verifier (Rates) - $job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mempool_downloaded_transactions_total{job=\"$job\"}[1m]) * 60",
     "legendFormat": "downloaded per min"
    },
    {
     "expr": "rate(mempool_verified_transactions_total{job=\"$job\"}[1m]) * 60",
     "legendFormat": "verified per min"
    },
    {
     "expr": "rate(mempool_queued_transactions_total{job=\"$job\"}[1m]) * 60",
     "legendFormat": "queued per min"
    }
   ]
  },
  {
   "title": "Downloaded Txs by Version - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (version) (mempool_downloaded_transactions_total{job=\"$job\"})",
     "legendFormat": "{{version}}"
    }
   ]
  }
 ]
}