FROM rust:1.81.0

# Set up Rust and cargo
RUN apt-get update && apt-get install git build-essential clang -y

# Set the working directory to the repo root
WORKDIR /app

# Copy the entire repository content (from parent directory)
COPY . .

# Build zebrad with the required features
RUN cargo build --release --package zebrad --bin zebrad --features="getblocktemplate-rpcs"

EXPOSE 18232

# Copy the config file from the testnet-single-node-deploy folder
COPY testnet-single-node-deploy/regtest-config.toml regtest-config.toml

# Run the zebra node
ENTRYPOINT ["target/release/zebrad", "-c", "regtest-config.toml"]
