//! Response type for the `validateaddress` RPC.

use crate::methods::get_block_template_rpcs::types::hex_data::HexData;

/// `validateaddress` response
#[derive(Clone, Default, Debug, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct Response {
    /// Whether the address is valid.
    ///
    /// If not, this is the only property returned.
    #[serde(rename = "isvalid")]
    pub is_valid: bool,

    /// The zcash address that has been validated.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,

    /// The hex encoded scriptPubKey generated by the address.
    #[serde(rename = "scriptPubKey")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub script_pub_key: Option<HexData>,

    /// The hex value of the raw public key.
    #[serde(rename = "pubkey")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pub_key: Option<HexData>,

    /// If the key is a script.
    #[serde(rename = "isscript")]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub is_script: Option<bool>,
}

impl Response {
    /// Creates an empty response with `isvalid` of false.
    pub fn invalid() -> Self {
        Self::default()
    }
}
