{
 "title": "network messages",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(zcash_net_in_bytes_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "inbound requests & responses - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (zebra_net_in_requests{job=\"$job\"})",
     "legendFormat": "Req::{{command}}"
    },
    {
     "expr": "sum by (command) (zebra_net_out_responses{job=\"$job\"})",
     "legendFormat": "Rsp::{{command}}"
    }
   ]
  },
  {
   "title": "outbound requests & responses - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (zebra_net_out_requests{job=\"$job\"})",
     "legendFormat": "Req::{{command}}"
    },
    {
     "expr": "sum by (command) (zebra_net_in_responses{job=\"$job\"})",
     "legendFormat": "Rsp::{{command}}"
    }
   ]
  },
  {
   "title": "canceled outbound requests - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (zebra_net_out_requests_canceled{job=\"$job\"})",
     "legendFormat": "Req::{{command}}"
    }
   ]
  },
  {
   "title": "inbound message types - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (zcash_net_in_messages{job=\"$job\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "outbound message types - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (command) (zcash_net_out_messages{job=\"$job\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "inbound message peers - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (addr) (zcash_net_in_messages{job=\"$job\"})",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "outbound message peers - $job",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "repeat": "job",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (addr) (zcash_net_out_messages{job=\"$job\"})",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}