// This file is @generated by prost-build.
/// Used by methods that take no arguments.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Empty {}
/// A block hash and height.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockHashAndHeight {
    /// The hash of the block in display order.
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// The height of the block in the chain.
    #[prost(uint32, tag = "2")]
    pub height: u32,
}
/// An encoded block and its hash.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockAndHash {
    /// The hash of the block in display order.
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    /// The encoded block data.
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// A request for a single block by hash or height from the best chain.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BlockRequest {
    /// The block to fetch, identified by either its hash or its height.
    ///
    /// A 32-byte value is interpreted as a block hash in display order; a 4-byte
    /// value is interpreted as a big-endian block height. Any other length is
    /// rejected.
    #[prost(bytes = "vec", tag = "1")]
    pub hash_or_height: ::prost::alloc::vec::Vec<u8>,
}
/// A request to subscribe to non-finalized state changes.
///
/// Deprecated: use ChainStateChangeRequest / ChainStateChange instead.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NonFinalizedStateChangeRequest {
    /// The hashes of the chain tips the caller already has, in display order.
    ///
    /// The server streams only the non-finalized blocks that come after these
    /// tips, skipping any block at or below a provided tip on the same chain.
    /// If empty, every block currently in the non-finalized state is sent, so an
    /// empty request is equivalent to the previous no-argument behavior.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub chain_tip_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// A request to subscribe to chain state changes.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainStateChangeRequest {
    /// The hashes of the chain tips the caller already has, in display order.
    ///
    /// The server streams only the non-finalized blocks that come after these
    /// tips, skipping any block at or below a provided tip on the same chain.
    /// If empty, every block currently in the non-finalized state is sent.
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub chain_tip_hashes: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// A single change in the chain state: either a new non-finalized block, or a
/// signal that the finalized chain tip advanced.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChainStateChangeMessage {
    /// The change that occurred: a new non-finalized block or a finalized-tip-change signal.
    #[prost(oneof = "chain_state_change_message::Change", tags = "1, 2")]
    pub change: ::core::option::Option<chain_state_change_message::Change>,
}
/// Nested message and enum types in `ChainStateChangeMessage`.
pub mod chain_state_change_message {
    /// The change that occurred: a new non-finalized block or a finalized-tip-change signal.
    #[derive(serde::Deserialize, serde::Serialize)]
    ///A change in the chain state: a new non-finalized block, or a finalized-tip-change signal.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Change {
        /// A new block in the non-finalized best chain.
        #[prost(message, tag = "1")]
        NonFinalizedBlock(super::BlockAndHash),
        /// The finalized chain tip advanced. A co-located follower uses this as a
        /// signal to catch its own finalized state up to the primary and publish
        /// its finalized tip; the block contents are obtained from the follower's
        /// own finalized state, not streamed here.
        #[prost(message, tag = "2")]
        FinalizedTipChange(super::BlockHashAndHeight),
    }
}
/// A transaction's unmined identifier.
///
/// `mined_id` is the 32-byte mined transaction id in display order. `auth_digest`
/// is the 32-byte authorizing-data digest in display order for v5+ (witnessed)
/// transactions, and empty for legacy (v1-v4) transactions, mirroring Zebra's
/// `UnminedTxId::Legacy` vs `UnminedTxId::Witnessed`.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnminedTxId {
    /// The mined transaction id, 32 bytes in display order.
    #[prost(bytes = "vec", tag = "1")]
    pub mined_id: ::prost::alloc::vec::Vec<u8>,
    /// The authorizing-data digest, 32 bytes in display order, or empty for a
    /// legacy (v1-v4) transaction.
    #[prost(bytes = "vec", tag = "2")]
    pub auth_digest: ::prost::alloc::vec::Vec<u8>,
}
/// Transactions entered the download/verify pipeline at the given stage.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolQueued {
    /// The transactions that were queued.
    #[prost(message, repeated, tag = "1")]
    pub tx_ids: ::prost::alloc::vec::Vec<UnminedTxId>,
    /// The pipeline stage the transactions reached.
    #[prost(enumeration = "QueuedStage", tag = "2")]
    pub stage: i32,
}
/// A transaction added to the verified mempool, carrying its content and the
/// fee/sigop/ZIP-317 metadata a follower needs without a network round-trip.
///
/// The content is fetched from the source's local mempool (in-process), not
/// streamed from a peer, so a follower never has to re-download an added tx.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolAdded {
    /// The serialized transaction. A follower reconstructs the unmined tx (and its
    /// id and size) from these bytes.
    #[prost(bytes = "vec", tag = "1")]
    pub transaction: ::prost::alloc::vec::Vec<u8>,
    /// The miner fee in zatoshi.
    #[prost(uint64, tag = "2")]
    pub miner_fee: u64,
    /// The legacy transparent sigop count (`GetLegacySigOpCount`).
    #[prost(uint32, tag = "3")]
    pub legacy_sigop_count: u32,
    /// The P2SH redeem-script sigop count (`GetP2SHSigOpCount`).
    #[prost(uint32, tag = "4")]
    pub p2sh_sigop_count: u32,
    /// The number of conventional actions, as defined by ZIP-317.
    #[prost(uint32, tag = "5")]
    pub conventional_actions: u32,
    /// The number of unpaid actions, as defined by ZIP-317 for block production.
    #[prost(uint32, tag = "6")]
    pub unpaid_actions: u32,
    /// The fee weight ratio, as defined by ZIP-317 for block production.
    #[prost(float, tag = "7")]
    pub fee_weight_ratio: f32,
}
/// Transactions removed from the mempool pipeline, all for the same reason.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolRemoved {
    /// The transactions that were removed.
    #[prost(message, repeated, tag = "1")]
    pub tx_ids: ::prost::alloc::vec::Vec<UnminedTxId>,
    /// Why the transactions were removed. "Mined" is not represented here: a mined
    /// tx leaves as a reason-less removal because the chain replica shows the
    /// block (design doc §5d), except where the source explicitly reports it.
    #[prost(oneof = "mempool_removed::Reason", tags = "2, 3, 4, 5, 6, 7")]
    pub reason: ::core::option::Option<mempool_removed::Reason>,
}
/// Nested message and enum types in `MempoolRemoved`.
pub mod mempool_removed {
    /// Why the transactions were removed. "Mined" is not represented here: a mined
    /// tx leaves as a reason-less removal because the chain replica shows the
    /// block (design doc §5d), except where the source explicitly reports it.
    #[derive(serde::Deserialize, serde::Serialize)]
    ///Why a set of transactions was removed from the mempool pipeline.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Reason {
        /// The transaction's content could not be downloaded.
        #[prost(message, tag = "2")]
        FailedDownload(super::Empty),
        /// The transaction did not pass verification. Carries a stable error code.
        #[prost(string, tag = "3")]
        FailedVerification(::prost::alloc::string::String),
        /// The transaction was mined onto the best chain.
        #[prost(message, tag = "4")]
        Mined(super::BlockHashAndHeight),
        /// The transaction expired before it could be mined.
        #[prost(message, tag = "5")]
        Expired(super::Empty),
        /// The transaction was evicted (e.g. ZIP-401 cost-limit eviction).
        #[prost(message, tag = "6")]
        Evicted(super::Empty),
        /// The transaction was re-queued for re-verification after a chain tip reset
        /// (design doc §5a). This doubles as the reorg marker for the batch.
        #[prost(message, tag = "7")]
        Reorged(super::Empty),
    }
}
/// A single transaction-lifecycle event observed in a mempool change cycle.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolEvent {
    /// The lifecycle event that occurred.
    #[prost(oneof = "mempool_event::Event", tags = "1, 2, 3")]
    pub event: ::core::option::Option<mempool_event::Event>,
}
/// Nested message and enum types in `MempoolEvent`.
pub mod mempool_event {
    /// The lifecycle event that occurred.
    #[derive(serde::Deserialize, serde::Serialize)]
    ///A transaction-lifecycle event: queued, added, or removed.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        /// Transactions entered the download/verify pipeline.
        #[prost(message, tag = "1")]
        Queued(super::MempoolQueued),
        /// A transaction was added to the verified mempool.
        #[prost(message, tag = "2")]
        Added(super::MempoolAdded),
        /// Transactions were removed from the mempool pipeline.
        #[prost(message, tag = "3")]
        Removed(super::MempoolRemoved),
    }
}
/// A per-cycle batch of mempool lifecycle events (design doc §5).
///
/// The wire unit is a batch, not an individual event: the source coalesces every
/// change observed in one mempool change cycle into a single batch, then stamps
/// it with the post-cycle checksum once the cycle's changes have settled. A
/// follower applies the events atomically, then recomputes and compares the
/// checksum; a mismatch is the divergence detector.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MempoolBatch {
    /// Every lifecycle event observed in this change cycle, in order. Includes a
    /// `reorged` removal marker for tip resets (design doc §5a).
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<MempoolEvent>,
    /// A hash of the source's full replica projection (verified + queued sets,
    /// design doc §3a-1) after this batch settles. The follower recomputes and
    /// compares; a mismatch triggers a re-bootstrap. Omitted on intermediate
    /// bootstrap chunks.
    #[prost(bytes = "vec", optional, tag = "2")]
    pub checksum: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// True on the final bootstrap batch: the preceding batches replayed current
    /// state; live cycles follow (the k8s SendInitialEvents bookmark).
    #[prost(bool, tag = "3")]
    pub initial_sync_complete: bool,
}
/// Metadata describing the node's finalized state, so a co-located read-only
/// follower can open this node's database at its exact runtime path.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateInfo {
    /// The live runtime path of the finalized-state database, as a UTF-8 string.
    /// For an ephemeral node this is a temporary directory that is removed when
    /// the node exits.
    #[prost(string, tag = "1")]
    pub db_path: ::prost::alloc::string::String,
    /// The database format version implemented by the node's running code
    /// (a semver string such as "27.0.0").
    #[prost(string, tag = "2")]
    pub db_format_version: ::prost::alloc::string::String,
    /// The Zcash network the node is running ("Mainnet" or "Testnet").
    #[prost(string, tag = "3")]
    pub network: ::prost::alloc::string::String,
}
/// The stage a queued transaction has reached in the download/verify pipeline.
#[derive(serde::Deserialize, serde::Serialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum QueuedStage {
    /// The transaction is queued and awaiting download of its content.
    AwaitingDownload = 0,
    /// The transaction has been downloaded and is awaiting verification.
    AwaitingVerification = 1,
}
impl QueuedStage {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AwaitingDownload => "AWAITING_DOWNLOAD",
            Self::AwaitingVerification => "AWAITING_VERIFICATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AWAITING_DOWNLOAD" => Some(Self::AwaitingDownload),
            "AWAITING_VERIFICATION" => Some(Self::AwaitingVerification),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod indexer_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct IndexerClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl IndexerClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> IndexerClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> IndexerClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            IndexerClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Notifies listeners of chain state changes: new non-finalized blocks
        /// interleaved with finalized-chain-tip-change signals.
        ///
        /// Callers may provide the hashes of the chain tips they already have so the
        /// server only streams non-finalized blocks after those tips. An empty request
        /// streams every block currently in the non-finalized state.
        ///
        /// This unifies (and supersedes) NonFinalizedStateChange, ChainTipChange, and
        /// GetBlock for a co-located read-state follower.
        pub async fn chain_state_change(
            &mut self,
            request: impl tonic::IntoRequest<super::ChainStateChangeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ChainStateChangeMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/ChainStateChange",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("zebra.indexer.rpc.Indexer", "ChainStateChange"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Notifies listeners of chain tip changes.
        ///
        /// Deprecated: use ChainStateChange instead.
        #[deprecated]
        pub async fn chain_tip_change(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BlockHashAndHeight>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/ChainTipChange",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zebra.indexer.rpc.Indexer", "ChainTipChange"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Notifies listeners of new blocks in the non-finalized state.
        ///
        /// Callers may provide the hashes of the chain tips they already have so the
        /// server only streams blocks after those tips. An empty request streams every
        /// block currently in the non-finalized state.
        ///
        /// Deprecated: use ChainStateChange instead.
        #[deprecated]
        pub async fn non_finalized_state_change(
            &mut self,
            request: impl tonic::IntoRequest<super::NonFinalizedStateChangeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::BlockAndHash>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/NonFinalizedStateChange",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "zebra.indexer.rpc.Indexer",
                        "NonFinalizedStateChange",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Streams the source mempool's transaction-lifecycle changes to a trusting
        /// follower (design doc §5).
        ///
        /// The server first replays the current mempool state as bootstrap batch(es) of
        /// `Queued`/`Added` events (the last carries `initial_sync_complete=true` and a
        /// checksum), then forwards one `MempoolBatch` per source change cycle, each
        /// carrying its post-cycle checksum. A checksum mismatch on the follower side is
        /// the divergence detector and triggers a reconnect/re-bootstrap.
        pub async fn sync_mempool(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MempoolBatch>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/SyncMempool",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zebra.indexer.rpc.Indexer", "SyncMempool"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Returns metadata about the node's finalized state (live database path,
        /// database format version, and network) so a co-located read-only follower
        /// can open this node's database directly.
        pub async fn get_state_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::StateInfo>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/GetStateInfo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zebra.indexer.rpc.Indexer", "GetStateInfo"));
            self.inner.unary(req, path, codec).await
        }
        /// Returns the block with the given hash or height from the best chain.
        ///
        /// Deprecated: a follower obtains finalized blocks from its own finalized
        /// state; use ChainStateChange for chain updates.
        #[deprecated]
        pub async fn get_block(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockRequest>,
        ) -> std::result::Result<tonic::Response<super::BlockAndHash>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic_prost::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/zebra.indexer.rpc.Indexer/GetBlock",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("zebra.indexer.rpc.Indexer", "GetBlock"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod indexer_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with IndexerServer.
    #[async_trait]
    pub trait Indexer: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the ChainStateChange method.
        type ChainStateChangeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::ChainStateChangeMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Notifies listeners of chain state changes: new non-finalized blocks
        /// interleaved with finalized-chain-tip-change signals.
        ///
        /// Callers may provide the hashes of the chain tips they already have so the
        /// server only streams non-finalized blocks after those tips. An empty request
        /// streams every block currently in the non-finalized state.
        ///
        /// This unifies (and supersedes) NonFinalizedStateChange, ChainTipChange, and
        /// GetBlock for a co-located read-state follower.
        async fn chain_state_change(
            &self,
            request: tonic::Request<super::ChainStateChangeRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ChainStateChangeStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the ChainTipChange method.
        type ChainTipChangeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BlockHashAndHeight, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Notifies listeners of chain tip changes.
        ///
        /// Deprecated: use ChainStateChange instead.
        async fn chain_tip_change(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<Self::ChainTipChangeStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the NonFinalizedStateChange method.
        type NonFinalizedStateChangeStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::BlockAndHash, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Notifies listeners of new blocks in the non-finalized state.
        ///
        /// Callers may provide the hashes of the chain tips they already have so the
        /// server only streams blocks after those tips. An empty request streams every
        /// block currently in the non-finalized state.
        ///
        /// Deprecated: use ChainStateChange instead.
        async fn non_finalized_state_change(
            &self,
            request: tonic::Request<super::NonFinalizedStateChangeRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::NonFinalizedStateChangeStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the SyncMempool method.
        type SyncMempoolStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::MempoolBatch, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Streams the source mempool's transaction-lifecycle changes to a trusting
        /// follower (design doc §5).
        ///
        /// The server first replays the current mempool state as bootstrap batch(es) of
        /// `Queued`/`Added` events (the last carries `initial_sync_complete=true` and a
        /// checksum), then forwards one `MempoolBatch` per source change cycle, each
        /// carrying its post-cycle checksum. A checksum mismatch on the follower side is
        /// the divergence detector and triggers a reconnect/re-bootstrap.
        async fn sync_mempool(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<
            tonic::Response<Self::SyncMempoolStream>,
            tonic::Status,
        >;
        /// Returns metadata about the node's finalized state (live database path,
        /// database format version, and network) so a co-located read-only follower
        /// can open this node's database directly.
        async fn get_state_info(
            &self,
            request: tonic::Request<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::StateInfo>, tonic::Status>;
        /// Returns the block with the given hash or height from the best chain.
        ///
        /// Deprecated: a follower obtains finalized blocks from its own finalized
        /// state; use ChainStateChange for chain updates.
        async fn get_block(
            &self,
            request: tonic::Request<super::BlockRequest>,
        ) -> std::result::Result<tonic::Response<super::BlockAndHash>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct IndexerServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> IndexerServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for IndexerServer<T>
    where
        T: Indexer,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/zebra.indexer.rpc.Indexer/ChainStateChange" => {
                    #[allow(non_camel_case_types)]
                    struct ChainStateChangeSvc<T: Indexer>(pub Arc<T>);
                    impl<
                        T: Indexer,
                    > tonic::server::ServerStreamingService<
                        super::ChainStateChangeRequest,
                    > for ChainStateChangeSvc<T> {
                        type Response = super::ChainStateChangeMessage;
                        type ResponseStream = T::ChainStateChangeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChainStateChangeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::chain_state_change(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChainStateChangeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zebra.indexer.rpc.Indexer/ChainTipChange" => {
                    #[allow(non_camel_case_types)]
                    struct ChainTipChangeSvc<T: Indexer>(pub Arc<T>);
                    impl<T: Indexer> tonic::server::ServerStreamingService<super::Empty>
                    for ChainTipChangeSvc<T> {
                        type Response = super::BlockHashAndHeight;
                        type ResponseStream = T::ChainTipChangeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::chain_tip_change(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChainTipChangeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zebra.indexer.rpc.Indexer/NonFinalizedStateChange" => {
                    #[allow(non_camel_case_types)]
                    struct NonFinalizedStateChangeSvc<T: Indexer>(pub Arc<T>);
                    impl<
                        T: Indexer,
                    > tonic::server::ServerStreamingService<
                        super::NonFinalizedStateChangeRequest,
                    > for NonFinalizedStateChangeSvc<T> {
                        type Response = super::BlockAndHash;
                        type ResponseStream = T::NonFinalizedStateChangeStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::NonFinalizedStateChangeRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::non_finalized_state_change(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = NonFinalizedStateChangeSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zebra.indexer.rpc.Indexer/SyncMempool" => {
                    #[allow(non_camel_case_types)]
                    struct SyncMempoolSvc<T: Indexer>(pub Arc<T>);
                    impl<T: Indexer> tonic::server::ServerStreamingService<super::Empty>
                    for SyncMempoolSvc<T> {
                        type Response = super::MempoolBatch;
                        type ResponseStream = T::SyncMempoolStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::sync_mempool(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SyncMempoolSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zebra.indexer.rpc.Indexer/GetStateInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetStateInfoSvc<T: Indexer>(pub Arc<T>);
                    impl<T: Indexer> tonic::server::UnaryService<super::Empty>
                    for GetStateInfoSvc<T> {
                        type Response = super::StateInfo;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::get_state_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStateInfoSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/zebra.indexer.rpc.Indexer/GetBlock" => {
                    #[allow(non_camel_case_types)]
                    struct GetBlockSvc<T: Indexer>(pub Arc<T>);
                    impl<T: Indexer> tonic::server::UnaryService<super::BlockRequest>
                    for GetBlockSvc<T> {
                        type Response = super::BlockAndHash;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::BlockRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Indexer>::get_block(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetBlockSvc(inner);
                        let codec = tonic_prost::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for IndexerServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "zebra.indexer.rpc.Indexer";
    impl<T> tonic::server::NamedService for IndexerServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
